### ISSUE TITLE
Can't remove steam mobile auth from accounts via steamguard-cli

### ISSUE THREAD

**Issue by dyc3** [dyc3/steamguard-cli#10]

**Comment by keesvv** [comment]
@dyc3 If this project is still being maintained, I would like to contribute to this issue, if you provide me some more details of the issue.

**Comment by dyc3** [comment]
I just haven't implemented an action to remove the authenticator from accounts. There's a function somewhere in the SteamAuth library to do this

**Comment by melvyn2** [comment]
@dyc3 You're halfway there: you already implemented removal for replacing an authenticator.
