### ISSUE TITLE
ERROR - Failed to link authenticator

### ISSUE THREAD

**Issue by xdfchvbjknml** [dyc3/steamguard-cli#105]
```
useruser:[user]:~$ steamguard setup
INFO - reading manifest from /home/user/.config/steamguard-cli/maFiles
Log in to the account that you want to link to steamguard-cli
Username: putis_spenser_here
Password: 
You should have received an email with a code.
Enter code: jrprh
ERROR - Failed to link authenticator. Account has not been linked. Unknown add authenticator status code: 2
useruser:[user]:~$ 

```
![image](https://user-images.githubusercontent.com/71084688/131365780-3afd6df0-6039-4437-8aa2-b03433ba9497.png)

installed from aur

**Comment by xdfchvbjknml** [comment]
solved.
i forgor:skull: to add phone to steam account

**Comment by dyc3** [comment]
Ah, yeah that's something I haven't fully reimplemented yet. IIRC, I have the endpoints already documented, just need the UI/UX for it in steamguard-cli
