### ISSUE TITLE
Can't access 2fa codes.

### ISSUE THREAD

**Issue by xdfchvbjknml** [dyc3/steamguard-cli#106]
I cant access 2fa codes to login into steam.
Command `steamguard-cli | xclip -selection clipboard` doesn't work.
Output:
```
useruser:[user]:~$ steamguard | xclip -selection clipboard
INFO - reading manifest from /home/user/.config/steamguard-cli/maFiles
useruser:[user]:~$ 
```
![Screenshot from 2021-08-31 16-10-49](https://user-images.githubusercontent.com/71084688/131517966-34b9b568-d7cf-4546-8c22-e92b75d3fba6.png)
(After executing command I have nothing in clipboard.)

**Comment by neckcen** [comment]
Did you try without xclip ? Because it won't work if you're using wayland for example.

**Comment by xdfchvbjknml** [comment]
Tried on both wayland and xorg.
(Doesn't work)

**Comment by dyc3** [comment]
That doesn't really answer the question. Try running

```bash
steamguard -v
```

and post the output.

**Comment by xdfchvbjknml** [comment]
`useruser:[user]:~$ steamguard -v
INFO - reading manifest from /home/user/.config/steamguard-cli/maFiles
DEBUG - loading manifest: "/home/user/.config/steamguard-cli/maFiles/manifest.json"
DEBUG - selected accounts: []
![Screenshot from 2021-09-05 13-07-02](https://user-images.githubusercontent.com/71084688/132124572-db8129da-4bc8-4c21-946b-595409b38d3d.png)
`

**Comment by dyc3** [comment]
There are no accounts in the manifest. You can use `import` or `setup` to add an account to the manifest.

**Comment by xdfchvbjknml** [comment]
I used `steamguard setup` and created the 2fa since I cant login to steam.

**Comment by dyc3** [comment]
What files are in `~/.config/steamguard-cli/maFiles` directory? If you see a file with the extension `.maFile`, then you can import it.

**Comment by xdfchvbjknml** [comment]
There's just manifest.json, but there used to be mafiles also, since I was trying to use tf2autobot, now I have only steam shared secret and steam identity secret

**Comment by dyc3** [comment]
Here's the json schema for an maFile:

```json
{
  "shared_secret": "",
  "serial_number": "",
  "revocation_code": "",
  "uri": "",
  "server_time": 0,
  "account_name": "",
  "token_gid": "",
  "identity_secret": "",
  "secret_1": "",
  "status": 1,
  "device_id": "",
  "fully_enrolled": true,
  "Session": {
    "SessionID": "",
    "SteamLogin": "",
    "SteamLoginSecure": "",
    "WebCookie": "",
    "OAuthToken": "",
    "SteamID": 0
  }
}
```

Try making a file with these contents, and put the shared secret, identity secret, and revocation code in the appropriate fields. Then you should be able to import the file.

Otherwise, you'll have to remove Steam guard from the account using the revocation code, and set it up again.

**Comment by xdfchvbjknml** [comment]
I didn't know how to recreate maFiles, so I just removed authenticator.
