### ISSUE TITLE
All codes are wrong.

### ISSUE THREAD

**Issue by xdfchvbjknml** [dyc3/steamguard-cli#108]
I tried to login today on steam, and got this every time I tried to login:
![Screenshot from 2021-09-06 21-23-26](https://user-images.githubusercontent.com/71084688/132255552-d7e8ef78-7db9-4280-bd91-673268f2c5bb.png)
I was able to login yesterday, but today it's not working.

**Comment by dyc3** [comment]
This might happen if the time used to generate the codes is wrong, but that shouldn't happen since we ping steam servers to grab the time.

The much more likely problem is that it's giving you a code for a different account.

Please post the output using `-v`.

**Comment by xdfchvbjknml** [comment]
I added only one account, so it shouldn't be giving codes from any other accounts.
`useruser:[user]:~$ steamguard -v
INFO - reading manifest from /home/user/.config/steamguard-cli/maFiles
DEBUG - loading manifest: "/home/user/.config/steamguard-cli/maFiles/manifest.json"
DEBUG - loading account: "/home/user/.config/steamguard-cli/maFiles/putis_spenser_here.maFile"
DEBUG - loading account: "/home/user/.config/steamguard-cli/maFiles/putis_spenser_here.maFile"
DEBUG - selected accounts: ["putis_spenser_here"]
NYXTT
useruser:[user]:~$ 
`
![Screenshot from 2021-09-06 21-40-09](https://user-images.githubusercontent.com/71084688/132256452-93a914a7-6ada-4261-9df7-52ee97d6dcb5.png)

**Comment by dyc3** [comment]
Make sure you are using the correct set of maFiles. You apparently have `~/.config/steamguard/maFiles` and `~/Documents/maFiles`.

**Comment by xdfchvbjknml** [comment]
No, `~/.config/steamguard/maFiles` are just copy of `~/Documents/maFiles`

**Comment by dyc3** [comment]
I'm not sure what the problem is then, sorry. The unit tests that check 2fa code generation are passing, so it's not an implementation problem. The only thing that's weird is that you have 2 manifest entries for the same account/file, which is a bug. Try removing the authenticator, deleting the manifest, and setting it back up again.
