### ISSUE TITLE
Keyring support

### ISSUE THREAD

**Issue by cjc7373** [dyc3/steamguard-cli#117]
By using libraries like [keyring-rs](https://github.com/hwchen/keyring-rs), one can store secrets into some platform-native credential managers, like serect service in Linux. Thus it can store serects into a password manager like KeePass.

Hopefully this could replace the encrypt and decrypt command.

**Comment by dyc3** [comment]
This is a great idea. Although, I still want to keep compatibility with SDA, so the encrypt and decrypt commands have to stay. Thanks for letting me know about this crate!

**Comment by dyc3** [comment]
What implications does this have for allowing users to back up their 2FA credentials? Would it be better to just use the keyring to store the encryption password instead of the shared secret and stuff?

**Comment by cjc7373** [comment]
I think this could be an opt-in feature. So people who enable it should have enough knowledge what they are doing and where to find their credentials.
