### ISSUE TITLE
Unknown add authenticator status code: 2

### ISSUE THREAD

**Issue by TheGitGuy007** [dyc3/steamguard-cli#118]
Hi,

Been trying to add my acocunt to steam. However, I keep getting this error "ERROR - Failed to link authenticator. Account has not been linked. Unknown add authenticator status code: 2"

I get the code via email, and once used I get this error.

The account was only created yesterday but has full access (it has money on the account etc..)

Thank you!

**Comment by dyc3** [comment]
This error is basically just steam saying "didn't work :shrug: try later".

duplicate of #116
