### ISSUE TITLE
Steamguard trade -a can overwhelm the ratelimit and it lags out

### ISSUE THREAD

**Issue by mirtisdyleris** [dyc3/steamguard-cli#130]
Hey :)

Sadly Steamguard trade -a frequently overwhelms the ratelimit. It just stops when the ratelimit is reached, rather it should just retry in 20 seconds or whatever. Im listing 10000s of items and it gets annoying quick bc I cant just go to bed and chill a bit and come back to have a couple of thousand items listed, rather I have to stick around and every 150-200 items or so I gotta restart this thing. Looping it with the .sh script you gave me doesnt work either sadly. Even if i set the sleep time to 20000.

Easiest solution would be to make it retry after 20-30 secs after hitting ratelimit. :)

<3

**Comment by dyc3** [comment]
`steamguard-cli` _really_ isn't meant to be used like this. It's meant to be used by a human, doing normal human stuff. If you are doing automated trading at that scale, you'd probably be better off integrating with the `steamguard` crate directly instead of through `steamguard-cli`.

The easiest solution for you would actually be to use the `-u` argument to specify an account name, loop through the accounts in bash, and retry if the exit code != 0.

**Comment by mirtisdyleris** [comment]
> The easiest solution for you would actually be to use the `-u` argument to specify an account name, loop through the accounts in bash, and retry if the exit code != 0.

I tried around but couldnt get it to work, could u please show me how I would do the retry thing? Ive tried around with $? -ne 0 but I cant get it to work :c

**Comment by dyc3** [comment]
Sorry but no, I've already told you a workaround. I'm not going to fix problems not related to steamguard-cli. Please read `--help`. It tells you specifically where to place arguments.

**Comment by mirtisdyleris** [comment]
> If there _is_ a problem with steamguard-cli that is preventing you from doing this, I will be happy to fix it. But you need to make that determination yourself, I am not going to do it for you.

Ive tried for like 1,5hr to find out how I would apply what u told me about the exit code but couldnt figure it out.. And it is kind of an issue with steamguard-cli as in that it breaks if the ratelimit is reached, which could be relatively easily circumvented, if you look at SDA, it does retry.

**Comment by mirtisdyleris** [comment]
Another error Im getting sometimes, dunno if you already know about this: "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.steampowered.com")), port: None, path: "/ITwoFactorService/QueryTime/v0001", query: None, fragment: None }, source: TimedOut }', steamguard/src/steamapi.rs:115:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

**Comment by dyc3** [comment]
I've added non-zero exit codes to trade confirmation failures. Pull down the master branch and compile it, let me know if it helps.
