### ISSUE TITLE
Application not opening on Manjaro (Arch) Linux

### ISSUE THREAD

**Issue by xitero** [dyc3/steamguard-cli#14]
I did all the steps correctly and had problems running the application with both available commands:
```
bash: build/steamguard: cannot execute binary file: Exec format error

make run
build/steamguard -v
build/steamguard: build/steamguard: cannot execute binary file
make: *** [makefile:9: run] Error 126
```

**Comment by dyc3** [comment]
Do you have the `mono` package installed?

**Comment by xitero** [comment]
Yes. I've reinstalled the requirements and now it worked. Thank you very much, your application is simple and effective, I will be using it from now on.

One question, can I accept exchanges for your application? If so, how? If this is not possible, do you want to add this?

**Comment by dyc3** [comment]
Yes, you can accept trade confirmations. See `steamguard --help`

**Comment by dyc3** [comment]
I just realized that it might not be in the help texts.

Use the `trade` action, e.g. `steamguard trade`

**Comment by xitero** [comment]
Hey man, this problem has returned, now in the Antergos. I already tried to reinstall the requirements but it did not work.
