### ISSUE TITLE
May require superfluous cookies when user login.

### ISSUE THREAD

**Issue by JK54** [dyc3/steamguard-cli#140]
In the code of login, judge session is None may require unneccessary cookies from steam, I think it should be cookies(compare with the SDA), correct me if I am wrong, thx.
steamguard-cli:
https://github.com/dyc3/steamguard-cli/blob/master/steamguard/src/userlogin.rs#L76
```rust
		if self.client.session.is_none() {
			self.client.update_session()?;
		}
....
```
SDA:
https://github.com/geel9/SteamAuth/blob/96ca6af3eb03d1a45f7fbff78851f055ba47c0d4/SteamAuth/UserLogin.cs#L48
```c#
        public LoginResult DoLogin()
        {
            var postData = new NameValueCollection();
            var cookies = _cookies;
            string response = null;

            if (cookies.Count == 0)
......
```

**Comment by dyc3** [comment]
IIRC, this is required. This line in SteamAuth has the side effect of adding session cookies.

https://github.com/geel9/SteamAuth/blob/96ca6af3eb03d1a45f7fbff78851f055ba47c0d4/SteamAuth/UserLogin.cs#L58
