### ISSUE TITLE
seems current .deb not supporting ubuntu 22.04

### ISSUE THREAD

**Issue by laptopmutia** [dyc3/steamguard-cli#147]
steamguard: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

whenever I call steamguard

I have tried to instal libssl.so.1.1 line in here https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di

but the problem is persist

**Comment by dyc3** [comment]
Seems like I haven't quite nailed down my releases yet.

As a workaround, you should be able to install it via cargo.

**Comment by dyc3** [comment]
Should be fixed in the latest release
