### ISSUE TITLE
[v0.4.4] Passkey now needs to be passed explicitly for encrypted maFiles

### ISSUE THREAD

**Issue by moppman** [dyc3/steamguard-cli#149]
Hi, 
I've just tried v0.4.4, and it looks like a passkey now needs to be passed explicitly via `-p` flag for encrypted maFiles, whereas before the passkey had been requested interactively (which is the right way to do it imho).
Or maybe I'm missing something?
Thanks!

**Comment by dyc3** [comment]
It *should* still be prompting you interactively for a passkey. Tested myself, can confirm that it does not prompt for your passkey Do you know what version this previously worked on?

**Comment by dyc3** [comment]
Opened a PR with a fix, I'll create a new release soon-ish.

**Comment by moppman** [comment]
>  Do you know what version this previously worked on?

v0.4.3 is working properly.
