### ISSUE TITLE
Failure | "WARN - accept confirmation result: Err(Condition failed: `resp.success`)"

### ISSUE THREAD

**Issue by goddemnet** [dyc3/steamguard-cli#160]
Hi.
For the second day, I can't confirm item exchanges and listings for sale. The codes are still being released.

I'm getting the following error:
```
WARN - accept confirmation result: Err(Condition failed: `resp.success`)
ERROR - Failed to respond to some confirmations.
INFO - Saving manifest and accounts...
```
![image](https://user-images.githubusercontent.com/67546666/179979711-ede45baa-35b8-48b2-9442-a890771cc342.png)

-
This was tested on several accounts.

**Comment by dyc3** [comment]
I'm not able to reproduce this. I'm assuming that this was a problem on steam's end, or you're being rate limited. If this is still happening for you, please share `-v debug` or `-v trace` logs.
