### ISSUE TITLE
[install] system requirement "x64" or "amd64" or do you mean "arm64"

### ISSUE THREAD

**Issue by arrowgent** [dyc3/steamguard-cli#163]
_sudo dpkg -i steamguard-cli_0.5.0-0.deb 
dpkg: error processing archive steamguard-cli_0.5.0-0.deb (--install):
 package architecture (x64) does not match system (amd64)
Errors were encountered while processing:
 steamguard-cli_0.5.0-0.deb_

`Linux 5.4.0-122-generic #138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

is this for mobile/pi only using **ARM64** or is it also **x86_64** aka **amd64**
?

**Comment by arrowgent** [comment]
noted that downloading the binary works fine for amd64
im not sure what you have broken in the .deb installer

**Comment by dyc3** [comment]
It's supposed to be for x86_64 aka amd64. I guess whatever documentation I was looking at was out of date.

**Comment by dyc3** [comment]
This should be fixed in the latest release.
