### ISSUE TITLE
[suggested] one liner with encryption - copy to clipboard fails

### ISSUE THREAD

**Issue by arrowgent** [dyc3/steamguard-cli#166]
https://github.com/dyc3/steamguard-cli#one-liners
`steamguard-cli | xclip -selection clipboard`

if your maFiles are encrypted with a passkey then this suggestion to clip will fail
first you have to put your password blindly without a prompt
then it copies both the "enter passphrase: XxXxX" and the code to the clipboard

if you dont have a passphrase its no issue
if you use `-p passKey` then it will not copy the `enter passphrase:` to the clipboard and only copies the steamguard code.

as noted in my bash script loop, `xsel -b` will print what is in the clipboard

ex:
`steamguard-cli | xclip -selection clipboard | xsel -b`

**Comment by dyc3** [comment]
Ah, yeah I could see that being annoying. As a workaround, you should be able to supply your encryption passkey as an environment variable to avoid getting prompted.
