### ISSUE TITLE
Can't confirm trades

### ISSUE THREAD

**Issue by Lyapsus** [dyc3/steamguard-cli#169]
`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/tui.rs:262:22` after enter in `steamguard trade`

**Comment by dyc3** [comment]
This specific bug is already fixed on master. The cause is steam is not returning any confirmations for the specified account. Make sure you are specifying the correct account with `-u`.

**Comment by Lyapsus** [comment]
Well I made sure, there is indeed zero visible confirmations
