### ISSUE TITLE
Panic with Capital Letters in Username

### ISSUE THREAD

**Issue by echo-84** [dyc3/steamguard-cli#171]
If capital letters are used in the username, the program panics and crashes after the password is entered. The SMS message is received but cant be entered to finish the activation leading to a failed attempt.

``thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Account not loaded', src/main.rs:420:59``

**Comment by dyc3** [comment]
I can confirm that this is reproducible. It is also weird af. Gonna try to fix this today.
