### ISSUE TITLE
ERROR - Failed to finalize: missing field `want_more`

### ISSUE THREAD

**Issue by hundredpinbowling** [dyc3/steamguard-cli#178]
I am having issues trying to run `steamguard-cli setup`. Firstly, the formatting of the prompts is confusing. For example, the program says "Log in to the account that you want to link to steamguard-cli," at which point you are supposed to put in your username, but it doesn't say 'Username:' until after "INFO - Logging in to MyUsername". I then find "Press any key to continue..." unclear. Am I  supposed to send some string? Can I just hit enter?
Anyway, after this confusion I am getting an error with regards to the variable `want_more'.

```
~ $ steamguard-cli setup           
INFO - reading manifest from /home/hundredpinbowling/.config/steamguard-cli/maFiles
ERROR - Did not find manifest in /home/hundredpinbowling/.config/steamguard-cli/maFiles
Would you like to create a manifest in /home/hundredpinbowling/.config/steamguard-cli/maFiles ? [Yn] Y
INFO - Saving manifest and accounts...
Log in to the account that you want to link to steamguard-cli
MyUsername
INFO - Logging in to MyUsername
Username: Password: 
You should have received an email with a code. If you did not, check your spam folder, or abort and try again.
ZZZZZ
INFO - Adding authenticator...
INFO - Saving manifest and accounts...
Enter code: Authenticator has not yet been linked. Before continuing with finalization, please take the time to write down your revocation code: R11111
Press any key to continue...
s
ERROR - Failed to finalize: missing field `want_more` at line 1 column 68
ERROR - missing field `want_more` at line 1 column 68
```

**Comment by dyc3** [comment]
Whoops, the "Press any key" message might be wrong -- probably should be "Press enter". I could have sworn I fixed the "Username" prompt not showing up, but I'll take a look at that too.

Otherwise, this is the first time I've seen this error. I'll have to test it on my end after my holiday vacation.

**Comment by s-leeq** [comment]
Same here, and couldn't print "Enter SMS code:" after pressing enter.

**Comment by aleksandrs-ledovskis** [comment]
Worked for me the following way - after "Press any key" prompt the `<Enter>` key was pressed. Afterwards, in the empty new row the SMS code was put and data entry finally confirmed with `<Enter>`.

**Comment by dyc3** [comment]
I believe the problem regarding prompts not appearing when they should is the result of rust's buffering stdout. This _should_ already be fixed but it's possible my fix was insufficient.

**Comment by aleksandrs-ledovskis** [comment]
FWIW, as I wasn't sure that steamguard-cli was supported to be run on macOS (if in case issue was due to some VT/terminal/shell nuances), I tested both on Iterm2 (with/without tmux) and Terminal.app, without any difference.

**Comment by dyc3** [comment]
MacOS is hard for me to support because I don't own a mac.

**Comment by aleksandrs-ledovskis** [comment]
Sure thing. I checked around and didn't found any well-known projects or test harnesses for CLI integration testing. Though there's a following nugget of an idea (https://stackoverflow.com/a/49451728).
So, in theory a test could be run via GitHub's CI runner on macOS (preferably even a matrix of OS'es - Linux, Mac, Win?), making a full integration testing routine by employing tmux and passing keys to it; checking the resulting screen for presence/lack of text.

**Comment by djibux** [comment]
> Worked for me the following way - after "Press any key" prompt the `<Enter>` key was pressed. Afterwards, in the empty new row the SMS code was put and data entry finally confirmed with `<Enter>`.

I experienced the issue with v0.7.0 but doing the above is a workaround.
Thanks.
