### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by Saalvage** [dyc3/steamguard-cli#179]
Trying to setup, when viewing the captcha in the browser all that is displayed is a random assortment of boxes, no text to be seen.
![image](https://user-images.githubusercontent.com/29021710/210393853-fe46fbff-7a58-4295-a1d7-c9c0fabe88b1.png)

**Comment by dyc3** [comment]
This does not appear to be an issue with steamguard-cli. Try using a different browser or image viewer.

**Comment by Saalvage** [comment]
I have tried both Chrome and Firefox, can you name a browser with which it works for you? I don't doubt that this isn't necessarily a steamguard-cli issue, but what is strange is that this behavior is consistent with entering a random number for the GID, meanwhile leaving the GID parameter empty renders the "STEAM!" text correctly..

**Comment by Saalvage** [comment]
For anyone stumbling on this, for future reference: It seems like CAPTCHA codes are only viewable with the IP that originally generated them!
