### ISSUE TITLE
Encrypt with a blank password, can't be decrypted afterwards

### ISSUE THREAD

**Issue by K4zoku** [dyc3/steamguard-cli#185]
![image](https://user-images.githubusercontent.com/34259386/226098888-8e5ca737-68c4-49c3-aebe-e2f054270c2f.png)

**Comment by dyc3** [comment]
Thanks for bringing this up. We shouldn't allow users to encrypt with a blank password, so this is definitely a validation bug.

**Comment by K4zoku** [comment]
> Thanks for bringing this up. We shouldn't allow users to encrypt with a blank password, so this is definitely a validation bug.

that the point 😉
