### ISSUE TITLE
Specific username fails in setup

### ISSUE THREAD

**Issue by FireStarW** [dyc3/steamguard-cli#19]
Sorry if this is more of a support thread but I seem to have come across a strange issue.

With the latest version of the program, attempting to run setup with an account with the username "2end_life" fails during the login step, after entering the password, (the correct one) the program always returns "GeneralFailure". This was tested on two different pcs, one running Ubuntu 16.04, the other with 17.04. 

If I use an account with a different name it makes it through the setup just fine.

**Comment by dyc3** [comment]
Sorry for not getting back to you sooner @FireStarW. Just to make sure we are talking about the same version, type `steamguard -h | head -n 1` and post the output.

**Comment by FireStarW** [comment]
steamguard-cli - v0.3.2.0

**Comment by dyc3** [comment]
Ok, thanks. Have you tried to log in and set up the mobile authenticator using SDA?

**Comment by FireStarW** [comment]
Yes, logging in with the problematic account fails on SDA as well. 
This isn't really a bug, but to add insult to injury attempting to import from android just crashes all variants of SDA I've tried, I'm sure if I tried a different computer at least that would work.

**Comment by dyc3** [comment]
Ok, in that case there is really nothing I can do about it. You could try talking to Steam Support, though I doubt it will help much. Sorry.
