### ISSUE TITLE
ITwoFactorService has changed, now requires `key` parameter

### ISSUE THREAD

**Issue by dyc3** [dyc3/steamguard-cli#192]
https://steamapi.xpaw.me/#ITwoFactorService

ITwoFactorService now requires a `key` parameter for:
- `AddAuthenticator`
- `FinalizeAddAuthenticator`
- `RemoveAuthenticator`

`QueryTime` seems to be unaffected

The `key` parameter seems to refer to a Steam Web API key: https://steamcommunity.com/dev/apikey

Although it may not be necessary? It's unclear if this code is out of date: 
- https://github.com/DoctorMcKay/node-steamcommunity/blob/353156008391f8474212681e381c275a81dacd57/components/twofactor.js#L19
- https://github.com/DoctorMcKay/node-steamcommunity/blob/353156008391f8474212681e381c275a81dacd57/components/webapi.js#L70

**Comment by nikicat** [comment]
I'm getting this error when trying to setup an account with 2fa:
```
TRACE - making request: POST https://api.steampowered.com/ITwoFactorService/AddAuthenticator/v0001
TRACE - raw add authenticator response: <html><head><title>Unauthorized</title></head><body><h1>Unauthorized</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>
```
