### ISSUE TITLE
GeneralFailure

### ISSUE THREAD

**Issue by Nikolay0054** [dyc3/steamguard-cli#21]
I have GeneralFailure when trying to setup new account with username "kolya0074" on ArchLinux. Maybe this is because my password has special characters?

**Comment by Nikolay0054** [comment]
I used Steam Desktop Authenticator to login in account

**Comment by dyc3** [comment]
GeneralFailure is a Steam error, and it's pretty cryptic. Best advice I can give you is try again later.

**Comment by vegasd** [comment]
I have the same issue for 2 accounts.

**Comment by dyc3** [comment]
Are you trying to paste your passwords when prompted?

**Comment by dyc3** [comment]
@Nikolay0054 just found out special characters don't work, see #24
