### ISSUE TITLE
Migrating SDA accounts failed

### ISSUE THREAD

**Issue by Szarikow** [dyc3/steamguard-cli#211]
### Version

steamguard-cli 0.8.1

### What happened?

ERROR - An unexpected error occurred during manifest migration: Failed to load some accounts: [DeserializationFailed(Error("invalid type: null, expected a string", line: 1, column: 766))]

Caused by:
    Failed to load some accounts: [DeserializationFailed(Error("invalid type: null, expected a string", line: 1, column: 766))]

### Steps To Reproduce

1. Import SDA maFiles into steamguard-cli appdata
2. Try to use trade or generate 2FA
3. Error

### Relevant log output

```Shell
INFO - reading manifest from C:\Users\User\AppData\Roaming\steamguard-cli/maFiles
DEBUG - loading manifest: "C:\\Users\\User\\AppData\\Roaming\\steamguard-cli/maFiles\\manifest.json"
INFO - Migrating manifest
DEBUG - deserializing manifest: version null
DEBUG - loading all accounts for migration
DEBUG - loading entry: "C:\\Users\\User\\AppData\\Roaming\\steamguard-cli/maFiles\\MyFirstAccountSteamIDHere.maFile"
DEBUG - loading entry: "C:\\Users\\User\\AppData\\Roaming\\steamguard-cli/maFiles\\MySecondAccountSteamIDHere.maFile"
ERROR - An unexpected error occurred during manifest migration: Failed to load some accounts: [DeserializationFailed(Error("invalid type: null, expected a string", line: 1, column: 766))]

Caused by:
    Failed to load some accounts: [DeserializationFailed(Error("invalid type: null, expected a string", line: 1, column: 766))]
```

**Comment by dyc3** [comment]
This indicates that there's something I didn't account for in the parsing. 

I've released v0.8.2. Could you please download it, run the following commands, and post the output?

```
steamguard.exe debug --print-stripped-json C:\Users\User\AppData\Roaming\steamguard-cli\maFiles\MyFirstAccountSteamIDHere.maFile
steamguard.exe debug --print-stripped-json C:\Users\User\AppData\Roaming\steamguard-cli\maFiles\MySecondAccountSteamIDHere.maFile
```

**Comment by LazySolitude** [comment]
I'm also having problems importing sda based maflies into the program.
I'm using a linux ubuntu distribution.
I'm not sure how to properly import the sda maflies and manifest.json into the program.
I tried deleting the manifest and adding it after I imported the maflies I get an error like this
/# steamguard import --sda
INFO - reading manifest from /root/.config/steamguard-cli/maFiles
ERROR - Did not find manifest in /root/.config/steamguard-cli/maFiles
Would you like to create a manifest in /root/.config/steamguard-cli/maFiles ? [Yn] Y
INFO - Saving manifest and accounts...
INFO - Saving manifest and accounts...
steamguard
INFO - reading manifest from /root/.config/steamguard-cli/maFiles
ERROR - Could not load accounts: Could not find an entry in the manifest for this account. Check your spelling.
ERROR - Could not find an entry in the manifest for this account. Check your spelling.
and when I check the manifest
there is no accounts in it.

**Comment by dyc3** [comment]
@LazySolitude, that looks like an unrelated issue, could you go open a new discussion post for it here? https://github.com/dyc3/steamguard-cli/discussions/new?category=q-a

**Comment by marvinlehmann** [comment]
I probably had the same issue yesterday. The OAuthToken for one of my accounts was null so I just set it to something random to it pass.

**Comment by Aurora15304** [comment]
![image](https://github.com/dyc3/steamguard-cli/assets/95676130/f3ea88e1-c1cd-4971-be58-d46afa219590)

**Comment by Szarikow** [comment]
Seems like that was the issue, fixed.
