### ISSUE TITLE
Unhandled exception after issuing passkey with special characters in prompt

### ISSUE THREAD

**Issue by loathingKernel** [dyc3/steamguard-cli#24]
In case I try to enter my passkey when steamguard-cli prompts for it, I am getting the following crash.
https://gist.github.com/loathingKernel/46a5ed026f318910c5c7347868523036

Unlike that case, when issuing the passkey as an argument to steamguard-cli, I am getting the crash only when the passkey is not escaped with quotes. It might not be limited to those, but in my case, my passkey contains the `lesser-than` and `greater-than` characters.

**Comment by dyc3** [comment]
Thanks for letting me know. Special characters currently do not work on password input. This is not intended behavior, and I am looking for an acceptable solution.

**Comment by dyc3** [comment]
Apparently, implementing an equivalent of `Console.ReadLine()` that doesn't echo input is hard. Currently trying to read from `stdin` using `Console.OpenStandardInput()`.

**Comment by dyc3** [comment]
`Console.OpenStandardInput()` then calling `ReadByte()` on the returned `Stream` seems to screw with `Console.ReadLine()`, because `Console.ReadLine()` won't wait until the user presses enter.

**Comment by dyc3** [comment]
I tried having bash handle the secure input by running `bash -c 'read -s password | echo $password'` and it might work.
