### ISSUE TITLE
'deny' accepts confirmations

### ISSUE THREAD

**Issue by ambidot** [dyc3/steamguard-cli#26]
i just did a test trade with this to a friend, opened `steamguard trade`, set 'deny' on the listing there, and pressed enter. it processed. i checked my trade history, and Steam showed the listing as accepted. the friend agreed it went through.

**Comment by dyc3** [comment]
Ah, shit. We can't have that now can we? I'll get right on it.

**Comment by dyc3** [comment]
Should be fixed now. Thanks for testing it out and letting me know.

**Comment by ambidot** [comment]
impressive turnaround thank you.
