### ISSUE TITLE
Search for `maFiles` directory adjacent to the executable so it can be portable 

### ISSUE THREAD

**Issue by AndyShade** [dyc3/steamguard-cli#275]
### Description

In first, thanks for your great work!
Add search maFiles in app root folder or in ./mafile directory near app or add possibility to point to maFile individually or dir via cli arguments.

**Comment by marvinlehmann** [comment]
You're able to specify the maFiles folder that contains the manifest and .maFile files. =)
```
    -m, --mafiles-path <MAFILES_PATH>
            Specify which folder your maFiles are in. This should be a path to a folder that
            contains manifest.json. Default: ~/.config/steamguard-cli/maFiles
            
            [env: STEAMGUARD_CLI_MAFILES=]
```

But I also think that it would be nice to automatically select the maFiles folder if one exists in the current working/app directory.

**Comment by marvinlehmann** [comment]
If I had to nitpick on #277: The maFiles next to the exe should be prioritized over config_dir & home_dir... but if neither of them exist.

```rust
fn get_mafiles_dir() -> String {
	let mut paths = vec![
		Path::new(&dirs::config_dir().unwrap()).join("steamguard-cli/maFiles"),
		Path::new(&dirs::home_dir().unwrap()).join("maFiles"),
	];
	if let Ok(current_exe) = std::env::current_exe() {
		paths.insert(0, current_exe.parent().unwrap().join("maFiles")); // insert at the index 0 for priority
	}

	for path in &paths {
		if path.join("manifest.json").is_file() {
			return path.to_str().unwrap().into();
		}
	}

	return paths[1].to_str().unwrap().into(); // index 1 so it doesn't default to adjacent dir for creation/setup
}
```

I'm not really familiar with Rust but this seems to do it for me - minimal changes. =)
