### ISSUE TITLE
v0.10.0 triggers Windows Defender

### ISSUE THREAD

**Issue by evodoc** [dyc3/steamguard-cli#276]
### Version

v0.10.0

### What happened?

When downloading Windows Defender put the file into quarantine claiming it has Trojan:Win32/Wacatac.B!ml.

### Steps To Reproduce

Download the file and see.

**Comment by dyc3** [comment]
Let's compare file hashes.

Download `v0.10.0` and upload it to this this tool: https://emn178.github.io/online-tools/sha256_checksum.html

What do you get for the checksum? It should be:

```
e77312511cd12c757a4696ac3c43922dcf1a255359f0c1d8ceea6072bf1fc194
```

**Comment by evodoc** [comment]
It matches.

**Comment by dyc3** [comment]
Huh. Well if it matches, then the executable is genuine and hasn't been tampered with. I don't know what I can do if windows defender decides to be cranky like that.

**Comment by dyc3** [comment]
I guess you'll have to exclude it from windows defender. Not much I can do.

**Comment by evodoc** [comment]
Windows Defender seems to have no problem with v0.10.1.
