### ISSUE TITLE
Cannot import mafile from SDA

### ISSUE THREAD

**Issue by oxifemps** [dyc3/steamguard-cli#286]
### Version

0.10.2

### What happened?

Hi, I am getting "missing field `steam_id` at line 1 column 816" when I try to import an older mafile from SDA. That's the exact mafile that are working on SDA, but steamguard-cli cannot recognize it.
I am running on ubuntu 22.04.

**Comment by dyc3** [comment]
Please post the full command you are running, and the output with `-v debug`.

**Comment by oxifemps** [comment]
> Please post the full command you are running, and the output with `-v debug`.

I have used the `steamguard import` command with my mafile on the folder and got this:

`INFO - reading manifest from /home/user/.config/steamguard-cli/maFiles`
`INFO - Saving manifest and accounts...`

After that, I tried to run `steamguard`:

`ERROR - Could not load accounts: Could not find an entry in the manifest for this account. Check your spelling.`
`ERROR - Could not find an entry in the manifest for this account. Check your spelling.`

Then I attempted to import using the `--files` option:

`steamguard import --files /home/user/.config/steamguard-cli/maFiles/account.maFile`

Finally, I received the following error:

`ERROR - Failed to import account: /home/user/.config/steamguard-cli/maFiles/account.maFile missing field `steam_id` at line 1 column 816`

Debug logs:

```
DEBUG - Args { global: GlobalArgs { username: None, all: false, mafiles_path: None, passkey: None, verbosity: Debug, no_update_check: false, http_proxy: None, proxy_credentials: None, danger_accept_invalid_certs: false }, sub: None, code: CodeCommand { offline: false } }
INFO - reading manifest from /home/user/.config/steamguard-cli/maFiles
DEBUG - loading manifest: "/home/user/.config/steamguard-cli/maFiles/manifest.json"
DEBUG - passkey was revoked from manifest
DEBUG - Performing auto-upgrade...
DEBUG - Manifest is up to date
ERROR - Could not load accounts: Could not find an entry in the manifest for this account. Check your spelling.
ERROR - Could not find an entry in the manifest for this account. Check your spelling.
DEBUG - Checking for updates to dyc3/steamguard-cli v0.10.2
DEBUG - No update available
```

**Comment by dyc3** [comment]
For SDA accounts, you need to also use the `--sda` argument.

**Comment by oxifemps** [comment]
Thank you, with `--sda` argument worked!
