### ISSUE TITLE
arch linux: use `-C target-cpu=native` in PKGBUILD

### ISSUE THREAD

**Issue by dyc3** [dyc3/steamguard-cli#291]
### Description

On arch linux, steamguard-cli is built from source for the current machine. This means it's safe to take advantage of whatever CPU features are available on the CPU. Adding the argument `-C target-cpu=native` to cargo build will allow the compiler to generate more optimized instructions.

**Comment by dumbasPL** [comment]
I Would argue against this. This is a simple CLI tool and the difference will be close to impossible to notice while potentially breaking pre-built packages. There are package repositories that offer pre-built packages from the AUR, doing this will mean that if somebody has an older CPU than whatever the build server is using then the package will be broken.

**Comment by dyc3** [comment]
Yeah this is probably not worth the effort.
