### ISSUE TITLE
confirmation error

### ISSUE THREAD

**Issue by Spawn944** [dyc3/steamguard-cli#292]
### Version

v0.10.2

### What happened?

I'm getting an error when trying to confirm many items (windows 10). This is happening with the latest version. I switched back to the previous version and it's working fine.

### Relevant log output

```Shell
INFO - abcd@hotmail.com: Checking for trade confirmations
WARN - accept confirmation result: Unknown error: Server responded with failure.
ERROR - Failed to respond to some confirmations.
INFO - Saving manifest and accounts...
```

**Comment by dyc3** [comment]
Which version did you switch back to? Can you post output with `-v debug`?

**Comment by dyc3** [comment]
Ok, I've encountered this a couple times, and you just have to wait and retry. Related: #293
