### ISSUE TITLE
Support for importing Winauth files

### ISSUE THREAD

**Issue by dyc3** [dyc3/steamguard-cli#295]
### Description

Winauth had support for steam, but it's not being maintained anymore.

https://github.com/winauth/winauth

**Comment by C0rn3j** [comment]
WinAuth users can for now manually transcribe the .txt export after urldecoding it into a .maFile looking like this (it probably has a ton of useless SDA-only parameters, but it works) https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/948#issuecomment-1738997065

To urldecode on Linux, do 
```bash
echo "pasteyourexporthere" | python3 -c "import sys; from urllib.parse import unquote; print(unquote(sys.stdin.read()));"
```

Using latest WinAuth beta export (3.5 is probably an older format), the format looks as such, one account per line:

```bash
otpauth://totp/Steam:<steamaccountname>?secret=<ABCDEFG1234_secret_dunno_what_for>&digits=5&issuer=Steam&deviceid=<URL_Escaped_device_name>&data=<url_encoded_data_json>
```

```json
{"steamid":"<steam_id>","status":1,"shared_secret":"<shared_secret>","serial_number":"<serial_number>","revocation_code":"<revocation_code>","uri":"<uri>","server_time":"<server_time>","account_name":"<steam_login_name>","token_gid":"<token_gid>","identity_secret":"<identity_secret>","secret_1":"<secret_1>","steamguard_scheme":"2"}
```

Should be as simple as spitting by line, checking if it starts with `otpauth://totp/Steam`, splitting by `&`, url decoding device name and data, and parsing the data JSON.

And instruct users to use the export from the [latest WinAuth beta](https://github.com/winauth/winauth/releases/tag/3.6.2).

**Comment by dyc3** [comment]
Thanks @C0rn3j, that's super useful.

**Comment by GenocideStomper** [comment]
Hi, sorry but I'm still confused with how I could import a winauth export. Does #331 add functionality to import the file directly? And if yes, how?
