### ISSUE TITLE
Can't add accounts just like SDA

### ISSUE THREAD

**Issue by OfficialFoam** [dyc3/steamguard-cli#303]
### Version

Latest

### What happened?

As SDA doesnt work to add accounts anymore I attempted to try this steamsli for an account and the same thing happens, doesnt work says try again in a few hours I attempted yesterday left it and tried again today and still doesnt work. It fails and only adds a number to the account please can you fix cheers.

**Comment by dyc3** [comment]
I can't fix the problem if you don't provide the info I need to fix it. There's a reason all those fields are on the bug report form.

You need to provide the actual version you are using -- "latest" is not sufficient. You also need to provide the log output with debug logging, add `-v debug` to the arguments.

**Comment by OfficialFoam** [comment]
I think its pretty self explanatory tho, im using the lastest repo / release, and when i use the setup function in your program after going through the adding account process it fails and says try again in a few hours.

**Comment by dyc3** [comment]
I just tried it and it works for me. Can you please provide the version and logs like I asked before?
