### ISSUE TITLE
Importing Steamguard-* files from Android

### ISSUE THREAD

**Issue by surfaceflinger** [dyc3/steamguard-cli#305]
### Description

Hi!

Would it be possible to add an option to import not only maFiles but also Steamguard-* files dumped from Android? I noticed some older issues about this and I could provide you with one of these files :)
Also, if you want to dig into the code instead, then ArchiSteamFarm supports these too.

**Comment by dyc3** [comment]
Do you mean steamguard files dumped from the Valve's official steam mobile app? Last I heard, you need a rooted android to do it, which I don't have. I couldn't find any code in ArchiSteamFarm that does this.

**Comment by dyc3** [comment]
If you can give me at least 1 or 2 sample files for accounts, I'll see what I can do. Don't give me your actual 2fa secrets though.

**Comment by surfaceflinger** [comment]
```
{"steamid":"X","shared_secret":"X","serial_number":"X","revocation_code":"X","uri":"otpauth:\/\/totp\/Steam:USERNAME?secret=X&issuer=Steam","server_time":"X","account_name":"USERNAME","token_gid":"X","identity_secret":"X","secret_1":"X","status":1,"steamguard_scheme":"2"}
```

And it appears that there's no new line at the end as printing it has a % at the end(?)
Not sure what's `steamguard_scheme` perhaps there are few schemas of those?

**Comment by dyc3** [comment]
If you take `shared_secret` and stick it into [cyberchef](https://gchq.github.io/CyberChef/) and base64 decode it, is it 20 bytes long? Same with `identity_secret`

**Comment by surfaceflinger** [comment]
Not sure if what I did is correct but I dragged `From Base64` onto the recipe field.
Both `shared_secret` and `identity_secret` decode into something not readable but `Output length` at the bottom shows 20.

**Comment by surfaceflinger** [comment]
Thank you! I'll try it out once I get back home :)

**Comment by surfaceflinger** [comment]
thanks, it works! if you could tag a new release it would be great :)

**Comment by dyc3** [comment]
Will do. Thanks for being so prompt and responsive :)
