### ISSUE TITLE
Error accept confirmations

### ISSUE THREAD

**Issue by AndriiSeeker** [dyc3/steamguard-cli#310]
### Version

last

### What happened?

Logs:
INFO - accepting all confirmations
WARN - accept confirmation result: Unknown error: Server responded with failure.
ERROR - Failed to respond to some confirmations.

Command: steamguard trade -a

**Comment by dyc3** [comment]
This is likely a Valve issue. Sometimes Valve's confirmation service just returns `success: false` and does not elaborate.

FYI "last" is not a version number. It's important to indicate the specific version because you might not actually be on the latest version.

**Comment by dyc3** [comment]
Closing because this is not actionable.
