### ISSUE TITLE
`.deb` in releases is not installable on debian 11 because of missing zstd support in dpkg

### ISSUE THREAD

**Issue by Darkinvo** [dyc3/steamguard-cli#314]
### Version

0.12.0-0.deb

### What happened?

$ sudo dpkg -i steamguard-cli_0.12.0-0.deb 

dpkg-deb: error: archive 'steamguard-cli_0.12.0-0.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive steamguard-cli_0.12.0-0.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 steamguard-cli_0.12.0-0.deb

### Steps To Reproduce

1. when install file.deb this show

**Comment by dyc3** [comment]
I'm not getting this error. Can you tell me what distro and distro version you are on?

**Comment by Darkinvo** [comment]
last version ->  0.12.0

**Comment by dyc3** [comment]
No, I'm asking what linux distro you are using. Ubuntu 22.04, Debian, etc.

**Comment by Darkinvo** [comment]
debain 11 .. sry !!

**Comment by dyc3** [comment]
Ah I see. I made the `.deb` on ubuntu 22.04. According to this [stack exchange answer](https://unix.stackexchange.com/a/669008), dpkg in debian 11 doesn't support zstd compression.

I'll have to update my packaging script to not use zstd compression. In the meantime though, you should still be able to use the binary from the releases, or [repackage it using the process described here](https://unix.stackexchange.com/a/745467).

**Comment by Darkinvo** [comment]
> Ah I see. I made the `.deb` on ubuntu 22.04. According to this [stack exchange answer](https://unix.stackexchange.com/a/669008), dpkg in debian 11 doesn't support zstd compression.
> 
> I'll have to update my packaging script to not use zstd compression. In the meantime though, you should still be able to use the binary from the releases, or [repackage it using the process described here](https://unix.stackexchange.com/a/745467).

## i do this but next error: 
`$ sudo apt-get  install /tmp/steamguard.deb`

>Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'steamguard-cli:x86-64' instead of '/tmp/steamguard.deb'
The following NEW packages will be installed:
  steamguard-cli:x86-64
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/4,250 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /tmp/steamguard.deb steamguard-cli x86-64 0.12.0 [4,250 kB]
dpkg: error processing archive /tmp/steamguard.deb (--unpack):
 package architecture (x86-64) does not match system (amd64)
Errors were encountered while processing:
 /tmp/steamguard.deb

**Comment by Darkinvo** [comment]
### i fix this with this commend after recomprssed:
### $ sudo dpkg -i --force-architecture steamguard.deb  # this fixed

but next error :D ->
###
> $ steamguard  setup

> INFO - reading manifest from /home/meti/.config/steamguard-cli/maFiles
ERROR - Did not find manifest in /home/meti/.config/steamguard-cli/maFiles
Would you like to create a manifest in /home/meti/.config/steamguard-cli/maFiles ? [Yn] y
INFO - Saving manifest and accounts...
Log in to the account that you want to link to steamguard-cli
Username: username-account
INFO - Logging in to username-account
Password: *************
Enter the 2fa code sent to your email: R6XM3
INFO - Polling for tokens... -- If this takes a long time, try logging in again.
INFO - Logged in successfully!
INFO - Adding authenticator...
ERROR - Failed to link authenticator. Account has not been linked. You are sending too many requests to Steam, and we got rate limited. Wait at least a couple hours and try again.
ERROR - You are sending too many requests to Steam, and we got rate limited. Wait at least a couple hours and try again.
