### ISSUE TITLE
ERROR - Pipe closed. (os error 232)

### ISSUE THREAD

**Issue by idimo** [dyc3/steamguard-cli#324]
### Version

steamguard v0.12.1

### What happened?

After a steam login attempt 4 messages appear.
Reading manifest, Approving login, Username and ERROR Pipe closed (os error 232). The Steam client does not log in. The tool was built from source on Windows 10.

**Comment by dyc3** [comment]
You need to post your full logs with `-v debug`

**Comment by idimo** [comment]
> You need to post your full logs with `-v debug`

DEBUG - Args { global: GlobalArgs { username: Some("accountname"), all: false, mafiles_path: None, passkey: None, verbosity: Debug, no_update_check: false, http_proxy: None, proxy_credentials: None, danger_accept_invalid_certs: false }, sub: Some(QrLogin(QrLoginCommand { url: "https://s.team/q/1/1080987710325945869" })), code: CodeCommand { offline: false } }
INFO - reading manifest from C:\Users\user\AppData\Roaming\steamguard-cli/maFiles
DEBUG - loading manifest: "C:\\Users\\user\\AppData\\Roaming\\steamguard-cli/maFiles\\manifest.json"
DEBUG - passkey was revoked from manifest
DEBUG - Performing auto-upgrade...
DEBUG - Manifest is up to date
DEBUG - loading entry: "C:\\Users\\user\\AppData\\Roaming\\steamguard-cli/maFiles\\accountname.maFile"
DEBUG - selected accounts: ["accountname"]
INFO - Approving login to accountname
INFO - Username: accountname
ERROR - Идет закрытие канала. (os error 232)
DEBUG - Checking for updates to dyc3/steamguard-cli v0.12.1
DEBUG - No update available

**Comment by dyc3** [comment]
I think it's failing to prompt you for your password.

**Comment by idimo** [comment]
> I think it's failing to prompt you for your password. I'll look into it, but I think it's more likely a problem with your system.

Can the password be supplied in some sort of file beforehand so that the script runs in fully automatic mode?

**Comment by dyc3** [comment]
Not at the moment, but that seems like something that would be good to have.

**Comment by idimo** [comment]
The new version prompts for password correctly. Thanks a lot for such a quick fix!

**Comment by Jamato-sUn** [comment]
Thanks a lot for this update!
