### ISSUE TITLE
Start deploying flatpak/snap packages

### ISSUE THREAD

**Issue by dyc3** [dyc3/steamguard-cli#33]
If you would like to see this, give this issue a thumbs up.

**Comment by protheory8** [comment]
Flatpak is usually not used for CLI program, as doing something like `flatpak run io.github.dyc3.SteamguardCli` just to invoke the program without arguments is not very comfortable. Still, I could try to package it as Flatpak if this is necessary.

**Comment by protheory8** [comment]
Snaps work fine with CLI programs, but I don't really know how to package apps as snaps. Could try though.

**Comment by dyc3** [comment]
After looking at this again, I'm somewhat inclined to not move forward with this.

- flatpak requires a really long command to invoke steamguard-cli
- snap is considerably more heavyweight than steamguard-cli warrants

I'd rather just provide packages for each distro.
