### ISSUE TITLE
Unable to run on Mac- "Cannot execute binary file"

### ISSUE THREAD

**Issue by Olimooseman** [dyc3/steamguard-cli#34]
After going through the full installation process, and make building successfully, I attempted to run steamguard. This is the message I received:

```
build/steamguard -v
build/steamguard: build/steamguard: cannot execute binary file
make: *** [run] Error 126
```

How do I fix this? Thanks!

EDIT: I'm on a Mac, if that helps

**Comment by dyc3** [comment]
I'm assuming you ran `make run`. Try running `mono build/steamguard`.

**Comment by Olimooseman** [comment]
Thanks so much- runs like a charm now! Sorry for the silly issue :)
