### ISSUE TITLE
BUG when password is changed and mafile used with new password

### ISSUE THREAD

**Issue by Luci515** [dyc3/steamguard-cli#340]
### Version

latest

### What happened?

INFO - Polling for tokens... -- If this takes a long time, try logging in again.
INFO - Logged in successfully!
INFO - xkjxo42543: Checking for trade confirmations
ERROR - Failed to get trade confirmations: Remote failure: Valve's server responded with a failure and said: Invalid authenticator
ERROR - Remote failure: Valve's server responded with a failure and said: Invalid authenticator
ERROR - Remote failure: Valve's server responded with a failure and said: Invalid authenticator

Keep in mind that I changed password of account, and then used mafile with new password.

**Comment by dyc3** [comment]
"latest" is not a valid version. It's important for me to know exactly what version you filed the issue for so I can properly narrow down where the problem is.

**Comment by dyc3** [comment]
Closing because this is not actionable.
