### ISSUE TITLE
steamguard-cli trade show nothing

### ISSUE THREAD

**Issue by buncis** [dyc3/steamguard-cli#342]
### Version

steamguard-cli 0.4.3

### What happened?

~ $ steamguard-cli trade
INFO - reading manifest from /home/bc/.config/steamguard-cli/maFiles
Enter encryption passkey: 
INFO - trade
INFO - Checking for trade confirmations

press a key other than enter to show the menu.

it show nothing after I press any key

![image](https://github.com/dyc3/steamguard-cli/assets/14258779/4a7e124b-162d-4f68-bf2d-7d3eee517a25)

using -v debug showing the menu but it still not accept my market listing pending

![image](https://github.com/dyc3/steamguard-cli/assets/14258779/435a663e-e19b-4c06-9cf5-ec028b6e641b)

my environment : 
~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

GNOME Version : 42.9
Windowing System X11

### Steps To Reproduce

~ $ steamguard-cli trade
INFO - reading manifest from /home/bc/.config/steamguard-cli/maFiles
Enter encryption passkey: 
INFO - trade
INFO - Checking for trade confirmations

press a key other than enter to show the menu.

it show nothing after I press any key

**Comment by dyc3** [comment]
Your steamguard-cli is extremely out of date. Update it, and try again.

**Comment by buncis** [comment]
lol, I have download latest release and do sudo dpkg -i for the new package yet it still not upodated

**Comment by dyc3** [comment]
to update using cargo, you can just `cargo install` it again and it'll download the latest
