### ISSUE TITLE
Error Authenticator finalization was unsuccessful

### ISSUE THREAD

**Issue by DeverBa** [dyc3/steamguard-cli#393]
### Version

0.14.0

### What happened?

The main problem is that for some reason I can't add Steam Guard to my account, the problem occurs at the last stage when I need to enter the code a second time to confirm that I want to add an authenticator.

### Steps To Reproduce

1. Enter the login
2. Enter the password
3. Log in to your account using a code from the mail
4. Entering a code to confirm the addition of an authenticator (There is an error here) 
**Error:  Authenticator finalization was unsuccessful. You may have entered the wrong confirm code in the previous step. Try again.**

### Relevant log output

```Shell
C:\Users\User\Desktop\SteamGuard>steamguard.exe -v debug setup
DEBUG Args { global: GlobalArgs { username: None, password: None, all: false, mafiles_path: None, passkey: None, verbosity: Debug, no_update_check: false, http_proxy: None, proxy_credentials: None, danger_accept_invalid_certs: false }, sub: Some(Setup(SetupCommand)), code: CodeCommand { offline: false } }
INFO reading manifest from C:\Users\User\AppData\Roaming\steamguard-cli/maFiles
DEBUG loading manifest: "C:\\Users\\User\\AppData\\Roaming\\steamguard-cli/maFiles\\manifest.json"
DEBUG passkey was revoked from manifest
DEBUG Performing auto-upgrade...
DEBUG Manifest is up to date
Log in to the account that you want to link to steamguard-cli
Username: INFO Logging in to **************
DEBUG prompting for password
Password:
DEBUG password is present
DEBUG starting login
DEBUG HTTP Request: GET https://api.steampowered.com/IAuthenticationService/GetPasswordRSAPublicKey/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
DEBUG HTTP Request: POST https://api.steampowered.com/IAuthenticationService/BeginAuthSessionViaCredentials/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
DEBUG auth session started
DEBUG got 2 confirmation methods: [
AllowedConfirmation {
confirmation_type: k_EAuthSessionGuardType_EmailCode,
associated_messsage: "outlook.com",
},
AllowedConfirmation {
confirmation_type: k_EAuthSessionGuardType_MachineToken,
associated_messsage: "",
},
]
Enter the 2fa code sent to your email: DEBUG HTTP Request: POST https://api.steampowered.com/IAuthenticationService/UpdateAuthSessionWithSteamGuardCode/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
INFO Polling for tokens... -- If this takes a long time, try logging in again.
DEBUG HTTP Request: POST https://api.steampowered.com/IAuthenticationService/PollAuthSessionStatus/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
INFO Logged in successfully!
INFO Adding authenticator...
DEBUG HTTP Request: POST https://api.steampowered.com/ITwoFactorService/AddAuthenticator/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
DEBUG adding account to manifest: **********
INFO Saving manifest and accounts...
DEBUG saving *********.maFile
DEBUG saving manifest
Authenticator has not yet been linked. Before continuing with finalization, please take the time to write down your revocation code: *****
Press enter to continue...DEBUG attempting link finalization
A code has been sent to the email address associated with this account.Enter email code: DEBUG HTTP Request: POST https://api.steampowered.com/ITwoFactorService/FinalizeAddAuthenticator/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
INFO Verifying authenticator status...
DEBUG HTTP Request: POST https://api.steampowered.com/ITwoFactorService/QueryStatus/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
DEBUG authenticator state: 0 -- did not actually finalize
INFO Saving manifest and accounts...
DEBUG saving manifest
ERROR Authenticator finalization was unsuccessful. You may have entered the wrong confirm code in the previous step. Try again.
DEBUG Checking for updates to dyc3/steamguard-cli v0.14.0
DEBUG No update available
```

**Comment by DeverBa** [comment]
> Thanks for actually reading the issue form and providing logs.
> 
> This is kinda weird. It looks like finalization was successful, but the verification check failed.
> 
> Post logs using this version. It should print slightly more information in the debug logs. [steamguard-cli-triage-393.zip](https://github.com/user-attachments/files/16085350/steamguard-cli-triage-393.zip)

<html><body>
<google-sheets-html-origin><style type="text/css"></style>
C:\Users\User\Desktop\SGCli-Test>steamguard.exe -v debug setup
--
DEBUG Args { global: GlobalArgs { username: None, password: None, all: false, mafiles_path: None, passkey: None, verbosity: Debug, no_update_check: false, http_proxy: None, proxy_credentials: None, danger_accept_invalid_certs: false }, sub: Some(Setup(SetupCommand)), code: CodeCommand { offline: false } }
INFO reading manifest from C:\Users\User\AppData\Roaming\steamguard-cli/maFiles
DEBUG loading manifest: "C:\\Users\\User\\AppData\\Roaming\\steamguard-cli/maFiles\\manifest.json"
DEBUG passkey was revoked from manifest
DEBUG Performing auto-upgrade...
DEBUG Manifest is up to date
Log in to the account that you want to link to steamguard-cli
Username: INFO Logging in to ***********
DEBUG prompting for password
Password:
DEBUG password is present
DEBUG starting login
DEBUG HTTP Request: GET https://api.steampowered.com/IAuthenticationService/GetPasswordRSAPublicKey/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
DEBUG HTTP Request: POST https://api.steampowered.com/IAuthenticationService/BeginAuthSessionViaCredentials/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
DEBUG auth session started
DEBUG got 2 confirmation methods: [
AllowedConfirmation {
confirmation_type: k_EAuthSessionGuardType_EmailCode,
associated_messsage: "outlook.com",
},
AllowedConfirmation {
confirmation_type: k_EAuthSessionGuardType_MachineToken,
associated_messsage: "",
},
]
Enter the 2fa code sent to your email: DEBUG HTTP Request: POST https://api.steampowered.com/IAuthenticationService/UpdateAuthSessionWithSteamGuardCode/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
INFO Polling for tokens... -- If this takes a long time, try logging in again.
DEBUG HTTP Request: POST https://api.steampowered.com/IAuthenticationService/PollAuthSessionStatus/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
INFO Logged in successfully!
INFO Adding authenticator...
DEBUG HTTP Request: POST https://api.steampowered.com/ITwoFactorService/AddAuthenticator/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
DEBUG adding account to manifest: ***********
INFO Saving manifest and accounts...
DEBUG saving ***********.maFile
DEBUG saving manifest
Authenticator has not yet been linked. Before continuing with finalization, please take the time to write down your revocation code: R01647
Press enter to continue...DEBUG attempting link finalization
A code has been sent to the email address associated with this account.Enter email code: DEBUG HTTP Request: POST https://api.steampowered.com/ITwoFactorService/FinalizeAddAuthenticator/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
INFO Verifying authenticator status...
DEBUG HTTP Request: POST https://api.steampowered.com/ITwoFactorService/QueryStatus/v1
DEBUG Response HTTP status: 200 OK
DEBUG HTTP Header x-eresult: 1
DEBUG authenticator state: 0 -- did not actually finalize
DEBUG full status: CTwoFactor_Status_Response {
state: Some(
0
),
inactivation_reason: None,
authenticator_type: None,
authenticator_allowed: Some(
true,
),
steamguard_scheme: Some(
1
),
token_gid: None,
email_validated: Some(
true,
),
device_identifier: None,
time_created: None,
revocation_attempts_remaining: None,
classified_agent: None,
allow_external_authenticator: None,
time_transferred: None,
version: None,
special_fields: SpecialFields {
unknown_fields: UnknownFields {
fields: None,
},
cached_size: CachedSize {
size: 0,
},
},
}
INFO Saving manifest and accounts...
DEBUG saving manifest
ERROR Authenticator finalization was unsuccessful. You may have entered the wrong confirm code in the previous step. Try again.
DEBUG Checking for updates to dyc3/steamguard-cli v0.14.0
DEBUG No update available


</body>
</html>

**Comment by dyc3** [comment]
If you add a phone number to your account, do you still get this problem?

**Comment by dyc3** [comment]
I'm unable to reproduce the issue on my end.
