### ISSUE TITLE
Family sharing confirmations aren't showing up with `steamguard confirm`

### ISSUE THREAD

**Issue by abdallahmehiz** [dyc3/steamguard-cli#398]
### Version

steamguard-cli 0.14.0

### What happened?

Steam recently added a new [family sharing feature](https://store.steampowered.com/news/app/593110/view/4149575031735702628)
This feature needs steam guard confirmations to work.

### Steps To Reproduce

1. use a different account to request a family share to/from your account
2. go check confirmations from `steamguard confirm`
3. empty

(screenshot below to show my friend is waiting on a confirmation from my end)
![image](https://github.com/user-attachments/assets/322b7694-d161-44d1-a59e-d17aa5f0d678)

### Relevant log output

```Shell
~ steamguard confirm
INFO reading manifest from /home/abdallah/.config/steamguard-cli/maFiles
INFO steamuser: Checking for confirmations
INFO obtaining new tokens
INFO Refreshing access token...
INFO Successfully refreshed access token, no need to prompt to log in.
INFO steamuser: No confirmations
INFO Saving manifest and accounts...
```

**Comment by dyc3** [comment]
I'm a little confused about this. The screenshot you posted looks like its waiting for the recipient of the invitation to accept it. If it required a mobile confirmation, I would think that it would say something like "waiting for confirmation", like trade offers do.

**Comment by abdallahmehiz** [comment]
> I'm a little confused about this. The screenshot you posted looks like its waiting for the recipient of the invitation to accept it. If it required a mobile confirmation, I would think that it would say something like "waiting for confirmation", like trade offers do.

The account in the screenshot is actually mine, my friend sent me that after inviting me to a family share group.

> Check if your friend got an email or a steam notification or something like that.

I have checked my email, it redirects me to the steam notifications tab. Interacting with the notification redirects me to the steam app's confirmations screen...

**Comment by dyc3** [comment]
Planning to look into this more next week.

**Comment by dyc3** [comment]
I'm unable to reproduce this issue. I get the mobile confirmation just fine:

On the joiner side:
![image](https://github.com/user-attachments/assets/675809bf-2dc1-4018-8e7c-3eb887650b09)

![image](https://github.com/user-attachments/assets/d4357582-476b-4097-9606-0bf9672115d3)

There is no confirmation needed to send an invite to a family, only to accept the invite.

**Comment by abdallahmehiz** [comment]
I don't if the the latest update fixed or if steam did something, but i can access the confirmations now.
Thanks!

**Comment by dyc3** [comment]
It was probably steam, since the feature is still in beta.
