### ISSUE TITLE
Error compiling archlinux error[E0282]: type annotations needed for `Box<_>`

### ISSUE THREAD

**Issue by als-creator** [dyc3/steamguard-cli#410]
### Version

0.14.1-1

### What happened?

yay -S steamguard-cli
 :: Существует 3 пакетов которые удволетворяют cargo
:: Репозиторий extra
    1) rust 2) rustup 
:: Репозиторий chaotic-aur
    3) rustup-git 

Введите номер (по умолчанию = 1): 
==> 1
 -> некорректный номер:  1

Введите номер (по умолчанию = 1): 
==> 1
AUR Explicit (1): steamguard-cli-0.14.1-1
Sync Make Dependency (1): rust-1:1.80.0-1
:: PKGBUILD up to date, skipping download: steamguard-cli
  1 steamguard-cli                   (файлы сборки существуют)
==> Пакеты, для которых требуется очистить кэш сборки?
==> [N]Нет [A]Все [Ab]Прервать [I]Установленные [No]Неустановленные или (1 2 3, 1-3, ^4)
==> 
  1 steamguard-cli                   (файлы сборки существуют)
==> Показать изменения?
==> [N]Нет [A]Все [Ab]Прервать [I]Установленные [No]Неустановленные или (1 2 3, 1-3, ^4)
==> 
==> Сборка пакета steamguard-cli 0.14.1-1 (Пн 05 авг 2024 17:25:50)
==> Получение исходных файлов...
  -> Найден steamguard-cli-0.14.1.tar.gz
==> ВНИМАНИЕ: Пропуск проверки PGP-подписей исходных файлов.
==> Проверка файлов source с использованием sha256sums...
    steamguard-cli-0.14.1.tar.gz ... Готово
:: Удалить зависимости для сборки после установки? [y/N] 
:: (1/1) Анализ SRCINFO: steamguard-cli
разрешение зависимостей...
проверка конфликтов...

Пакет (1)   Новая версия  Изменение размера

extra/rust  1:1.80.0-1           259,78 MiB

Будет установлено:  259,78 MiB

:: Приступить к установке? [Y/n] 
(1/1) проверка ключей                                                                                              [--------------------------------------------------------------------] 100%
(1/1) проверка целостности пакета                                                                                  [--------------------------------------------------------------------] 100%
(1/1) загрузка файлов пакетов                                                                                      [--------------------------------------------------------------------] 100%
(1/1) проверка конфликтов файлов                                                                                   [--------------------------------------------------------------------] 100%
(1/1) проверка доступного места                                                                                    [--------------------------------------------------------------------] 100%
:: Обработка изменений пакета...
(1/1) установка rust                                                                                               [--------------------------------------------------------------------] 100%
Дополнительные зависимости для 'rust'
    gdb: rust-gdb script
    lldb: rust-lldb script
:: Запуск post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Сборка пакета steamguard-cli 0.14.1-1 (Пн 05 авг 2024 17:25:57)
==> Проверка зависимостей для запуска...
==> Проверка зависимостей для сборки...
==> Получение исходных файлов...
  -> Найден steamguard-cli-0.14.1.tar.gz
==> Проверка файлов source с использованием sha256sums...
    steamguard-cli-0.14.1.tar.gz ... Готово
==> Удаление директории '$srcdir/'...
==> Распаковка исходных файлов...
  -> Распаковка 'steamguard-cli-0.14.1.tar.gz' с помощью bsdtar
==> Запускается prepare()...
==> Исходные файлы готовы.
==> Сборка пакета steamguard-cli 0.14.1-1 (Пн 05 авг 2024 17:25:59)
==> Проверка зависимостей для запуска...
==> Проверка зависимостей для сборки...
==> ВНИМАНИЕ: Использование существующего дерева исходных файлов в '$srcdir/'
==> Удаление директории '$pkgdir/'...
==> Запускается build()...
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.84
   Compiling unicode-ident v1.0.9
   Compiling libc v0.2.153
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling memchr v2.5.0
   Compiling log v0.4.19
   Compiling quote v1.0.36
   Compiling syn v2.0.66
   Compiling typenum v1.16.0
   Compiling generic-array v0.14.7
   Compiling futures-core v0.3.28
   Compiling scopeguard v1.1.0
   Compiling crossbeam-utils v0.8.16
   Compiling thiserror v1.0.61
   Compiling libm v0.2.7
   Compiling num-traits v0.2.15
   Compiling once_cell v1.19.0
   Compiling pin-project-lite v0.2.10
   Compiling num_cpus v1.16.0
   Compiling getrandom v0.2.10
   Compiling subtle v2.5.0
   Compiling serde v1.0.165
   Compiling const-oid v0.9.3
   Compiling syn v1.0.109
   Compiling crypto-common v0.1.6
   Compiling lock_api v0.4.10
   Compiling num-integer v0.1.45
   Compiling itoa v1.0.7
   Compiling io-lifetimes v1.0.11
   Compiling anyhow v1.0.71
   Compiling futures-io v0.3.28
   Compiling block-buffer v0.10.4
   Compiling socket2 v0.4.9
   Compiling memoffset v0.9.0
   Compiling slab v0.4.8
   Compiling smallvec v1.13.2
   Compiling digest v0.10.7
   Compiling crossbeam-epoch v0.9.15
   Compiling bitflags v1.3.2
   Compiling equivalent v1.0.0
   Compiling bytes v1.4.0
   Compiling hashbrown v0.14.0
   Compiling simd-adler32 v0.3.7
   Compiling indexmap v2.0.0
   Compiling aho-corasick v1.0.2
   Compiling spin v0.9.8
   Compiling rand_core v0.6.4
   Compiling mio v0.8.11
   Compiling num-bigint v0.4.3
   Compiling winnow v0.4.7
   Compiling thiserror-impl v1.0.61
   Compiling serde_derive v1.0.165
   Compiling zeroize_derive v1.4.2
   Compiling zeroize v1.6.0
   Compiling regex-syntax v0.7.2
   Compiling toml_datetime v0.6.6
   Compiling either v1.8.1
   Compiling futures-task v0.3.28
   Compiling futures-sink v0.3.28
   Compiling toml_edit v0.19.11
   Compiling regex v1.8.4
   Compiling tokio v1.29.1
   Compiling num-rational v0.4.1
   Compiling crc32fast v1.3.2
   Compiling byteorder v1.4.3
   Compiling adler v1.0.2
   Compiling futures-util v0.3.28
   Compiling rayon-core v1.11.0
   Compiling miniz_oxide v0.7.1
   Compiling proc-macro-crate v1.3.1
   Compiling crossbeam-deque v0.8.3
   Compiling futures-macro v0.3.28
   Compiling crossbeam-channel v0.5.8
   Compiling protobuf v3.2.0
   Compiling cc v1.0.94
   Compiling event-listener v2.5.3
   Compiling base64ct v1.6.0
   Compiling pin-utils v0.1.0
   Compiling ring v0.17.8
   Compiling tracing-attributes v0.1.26
   Compiling tracing-core v0.1.31
   Compiling unicase v2.6.0
   Compiling fnv v1.0.7
   Compiling tinyvec_macros v0.1.1
   Compiling minimal-lexical v0.2.1
   Compiling tinyvec v1.6.0
   Compiling nom v7.1.3
   Compiling flate2 v1.0.26
   Compiling tracing v0.1.37
   Compiling concurrent-queue v2.2.0
   Compiling num-iter v0.1.43
   Compiling parking v2.1.0
   Compiling waker-fn v1.1.0
   Compiling rustls-pki-types v1.7.0
   Compiling ppv-lite86 v0.2.17
   Compiling cpufeatures v0.2.8
   Compiling rustix v0.37.25
   Compiling fastrand v1.9.0
   Compiling futures-lite v1.13.0
   Compiling rand_chacha v0.3.1
   Compiling unicode-normalization v0.1.22
   Compiling http v1.1.0
   Compiling rayon v1.7.0
   Compiling async-lock v2.7.0
   Compiling zvariant_utils v1.0.1
   Compiling indexmap v1.9.3
   Compiling memoffset v0.7.1
   Compiling tempfile v3.6.0
   Compiling built v0.7.3
   Compiling unicode-bidi v0.3.13
   Compiling paste v1.0.15
   Compiling httparse v1.8.0
   Compiling aligned-vec v0.5.0
   Compiling arrayvec v0.7.4
   Compiling static_assertions v1.1.0
   Compiling percent-encoding v2.3.0
   Compiling linux-raw-sys v0.3.8
   Compiling time-core v0.1.1
   Compiling untrusted v0.9.0
   Compiling futures-channel v0.3.28
   Compiling time-macros v0.2.9
   Compiling v_frame v0.3.8
   Compiling rav1e v0.7.1
   Compiling http-body v1.0.0
   Compiling rand v0.8.5
   Compiling pem-rfc7468 v0.7.0
   Compiling protobuf-support v3.2.0
   Compiling profiling-procmacros v1.0.15
   Compiling pin-project-internal v1.1.5
   Compiling enumflags2_derive v0.7.7
   Compiling polling v2.8.0
   Compiling hashbrown v0.12.3
   Compiling rustversion v1.0.14
   Compiling spin v0.5.2
   Compiling try-lock v0.2.4
   Compiling ryu v1.0.13
   Compiling async-task v4.4.0
   Compiling bytemuck v1.13.1
   Compiling serde_json v1.0.99
   Compiling rustls v0.22.4
   Compiling want v0.3.1
   Compiling lazy_static v1.4.0
   Compiling which v4.4.0
   Compiling time v0.3.22
   Compiling enumflags2 v0.7.7
   Compiling pin-project v1.1.5
error[E0282]: type annotations needed for `Box<_>`
  --> /home/als/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.22/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling profiling v1.0.15
   Compiling der v0.7.7
   Compiling rustls-webpki v0.102.4
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
 -> ошибка сборки: steamguard-cli-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
steamguard-cli - exit status 4

### Relevant log output

```Shell
-> No AUR package found for debug
AUR Explicit (1): steamguard-cli-0.14.1-1
:: PKGBUILD up to date, skipping download: steamguard-cli
  1 steamguard-cli                   (файлы сборки существуют)
==> Пакеты, для которых требуется очистить кэш сборки?
==> [N]Нет [A]Все [Ab]Прервать [I]Установленные [No]Неустановленные или (1 2 3, 1-3, ^4)
==> 
  1 steamguard-cli                   (файлы сборки существуют)
==> Показать изменения?
==> [N]Нет [A]Все [Ab]Прервать [I]Установленные [No]Неустановленные или (1 2 3, 1-3, ^4)
==> 
==> Сборка пакета steamguard-cli 0.14.1-1 (Пн 05 авг 2024 18:22:10)
==> Получение исходных файлов...
  -> Найден steamguard-cli-0.14.1.tar.gz
==> ВНИМАНИЕ: Пропуск проверки PGP-подписей исходных файлов.
==> Проверка файлов source с использованием sha256sums...
    steamguard-cli-0.14.1.tar.gz ... Готово
:: (1/1) Анализ SRCINFO: steamguard-cli
==> Сборка пакета steamguard-cli 0.14.1-1 (Пн 05 авг 2024 18:22:11)
==> Проверка зависимостей для запуска...
==> Проверка зависимостей для сборки...
==> Получение исходных файлов...
  -> Найден steamguard-cli-0.14.1.tar.gz
==> Проверка файлов source с использованием sha256sums...
    steamguard-cli-0.14.1.tar.gz ... Готово
==> Удаление директории '$srcdir/'...
==> Распаковка исходных файлов...
  -> Распаковка 'steamguard-cli-0.14.1.tar.gz' с помощью bsdtar
==> Запускается prepare()...
==> Исходные файлы готовы.
==> Сборка пакета steamguard-cli 0.14.1-1 (Пн 05 авг 2024 18:22:14)
==> Проверка зависимостей для запуска...
==> Проверка зависимостей для сборки...
==> ВНИМАНИЕ: Использование существующего дерева исходных файлов в '$srcdir/'
==> Удаление директории '$pkgdir/'...
==> Запускается build()...
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.84
   Compiling unicode-ident v1.0.9
   Compiling libc v0.2.153
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling memchr v2.5.0
   Compiling log v0.4.19
   Compiling quote v1.0.36
   Compiling syn v2.0.66
   Compiling typenum v1.16.0
   Compiling generic-array v0.14.7
   Compiling futures-core v0.3.28
   Compiling crossbeam-utils v0.8.16
   Compiling scopeguard v1.1.0
   Compiling thiserror v1.0.61
   Compiling libm v0.2.7
   Compiling num-traits v0.2.15
   Compiling once_cell v1.19.0
   Compiling pin-project-lite v0.2.10
   Compiling num_cpus v1.16.0
   Compiling getrandom v0.2.10
   Compiling subtle v2.5.0
   Compiling serde v1.0.165
   Compiling const-oid v0.9.3
   Compiling syn v1.0.109
   Compiling crypto-common v0.1.6
   Compiling num-integer v0.1.45
   Compiling lock_api v0.4.10
   Compiling io-lifetimes v1.0.11
   Compiling itoa v1.0.7
   Compiling anyhow v1.0.71
   Compiling futures-io v0.3.28
   Compiling block-buffer v0.10.4
   Compiling socket2 v0.4.9
   Compiling memoffset v0.9.0
   Compiling slab v0.4.8
   Compiling smallvec v1.13.2
   Compiling digest v0.10.7
   Compiling crossbeam-epoch v0.9.15
   Compiling bitflags v1.3.2
   Compiling bytes v1.4.0
   Compiling hashbrown v0.14.0
   Compiling equivalent v1.0.0
   Compiling simd-adler32 v0.3.7
   Compiling indexmap v2.0.0
   Compiling aho-corasick v1.0.2
   Compiling spin v0.9.8
   Compiling rand_core v0.6.4
   Compiling mio v0.8.11
   Compiling num-bigint v0.4.3
   Compiling toml_datetime v0.6.6
   Compiling regex-syntax v0.7.2
   Compiling thiserror-impl v1.0.61
   Compiling serde_derive v1.0.165
   Compiling zeroize_derive v1.4.2
   Compiling zeroize v1.6.0
   Compiling winnow v0.4.7
   Compiling either v1.8.1
   Compiling futures-sink v0.3.28
   Compiling futures-task v0.3.28
   Compiling regex v1.8.4
   Compiling tokio v1.29.1
   Compiling num-rational v0.4.1
   Compiling adler v1.0.2
   Compiling byteorder v1.4.3
   Compiling toml_edit v0.19.11
   Compiling crc32fast v1.3.2
   Compiling futures-util v0.3.28
   Compiling rayon-core v1.11.0
   Compiling miniz_oxide v0.7.1
   Compiling proc-macro-crate v1.3.1
   Compiling crossbeam-deque v0.8.3
   Compiling futures-macro v0.3.28
   Compiling crossbeam-channel v0.5.8
   Compiling event-listener v2.5.3
   Compiling cc v1.0.94
   Compiling base64ct v1.6.0
   Compiling protobuf v3.2.0
   Compiling pin-utils v0.1.0
   Compiling ring v0.17.8
   Compiling tracing-attributes v0.1.26
   Compiling tracing-core v0.1.31
   Compiling unicase v2.6.0
   Compiling tinyvec_macros v0.1.1
   Compiling minimal-lexical v0.2.1
   Compiling fnv v1.0.7
   Compiling nom v7.1.3
   Compiling tinyvec v1.6.0
   Compiling flate2 v1.0.26
   Compiling tracing v0.1.37
   Compiling concurrent-queue v2.2.0
   Compiling num-iter v0.1.43
   Compiling rustls-pki-types v1.7.0
   Compiling waker-fn v1.1.0
   Compiling parking v2.1.0
   Compiling ppv-lite86 v0.2.17
   Compiling rustix v0.37.25
   Compiling fastrand v1.9.0
   Compiling cpufeatures v0.2.8
   Compiling futures-lite v1.13.0
   Compiling rand_chacha v0.3.1
   Compiling unicode-normalization v0.1.22
   Compiling http v1.1.0
   Compiling rayon v1.7.0
   Compiling async-lock v2.7.0
   Compiling zvariant_utils v1.0.1
   Compiling tempfile v3.6.0
   Compiling indexmap v1.9.3
   Compiling memoffset v0.7.1
   Compiling httparse v1.8.0
   Compiling built v0.7.3
   Compiling time-core v0.1.1
   Compiling linux-raw-sys v0.3.8
   Compiling static_assertions v1.1.0
   Compiling aligned-vec v0.5.0
   Compiling unicode-bidi v0.3.13
   Compiling percent-encoding v2.3.0
   Compiling futures-channel v0.3.28
   Compiling paste v1.0.15
   Compiling untrusted v0.9.0
   Compiling arrayvec v0.7.4
   Compiling v_frame v0.3.8
   Compiling rav1e v0.7.1
   Compiling time-macros v0.2.9
   Compiling http-body v1.0.0
   Compiling rand v0.8.5
   Compiling pem-rfc7468 v0.7.0
   Compiling protobuf-support v3.2.0
   Compiling enumflags2_derive v0.7.7
   Compiling profiling-procmacros v1.0.15
   Compiling pin-project-internal v1.1.5
   Compiling polling v2.8.0
   Compiling hashbrown v0.12.3
   Compiling try-lock v0.2.4
   Compiling rustversion v1.0.14
   Compiling bytemuck v1.13.1
   Compiling async-task v4.4.0
   Compiling rustls v0.22.4
   Compiling ryu v1.0.13
   Compiling spin v0.5.2
   Compiling serde_json v1.0.99
   Compiling lazy_static v1.4.0
   Compiling time v0.3.22
   Compiling which v4.4.0
error[E0282]: type annotations needed for `Box<_>`
  --> /home/als/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.22/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling want v0.3.1
   Compiling enumflags2 v0.7.7
   Compiling pin-project v1.1.5
   Compiling profiling v1.0.15
   Compiling der v0.7.7
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
 -> ошибка сборки: steamguard-cli-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
steamguard-cli - exit status 4
```

**Comment by dyc3** [comment]
This should have been fixed in #405. Try installing `steamguard-cli-git`. In the meantime, I'll publish a new release.

**Comment by als-creator** [comment]
AppImage planned?

**Comment by dyc3** [comment]
No. steamguard-cli can be built so that it's completely statically linked, so it's not really necessary to bundle it into an appimage.
