### ISSUE TITLE
why steamguard.exe detected as a virus?

### ISSUE THREAD

**Issue by cheetah747** [dyc3/steamguard-cli#413]
### Version

0.14.2

### What happened?

when I download the steamguard.exe, my computer detected that it was a virus called Ransom/Filecoder.c

### Steps To Reproduce

1.download
2.detected as virus
3.deleted

### Relevant log output

```Shell
detected as Ransom/Filecoder.c
```

**Comment by dyc3** [comment]
As long as you downloaded it from [this repo's releases](https://github.com/dyc3/steamguard-cli/releases), it's safe. There's nothing I can do about false positives from antivirus software.
