### ISSUE TITLE
"stream did not contain valid UTF-8" when entering password with unicode chars

### ISSUE THREAD

**Issue by Infantile-bastard** [dyc3/steamguard-cli#419]
### Version

steamguard-cli 0.14.2

### What happened?

An error pops up related to entering the password.
Part of the password is written in Russian (due to my carelessness). 
I tried to fix the password, but it requires confirmation from the mobile app. I did not find this button in the cli. Tell me, please, is there any way to solve this problem without deleting Steam Guard (I don't want to get a 2-week ban), or is this the only way out?
![1](https://github.com/user-attachments/assets/9943ec67-224b-4053-92ca-232a30592aff)
![2](https://github.com/user-attachments/assets/b413b0af-31a7-43f2-a52c-dffd7655c294)

"This is a bug in steamguard-cli. Please file an issue on github. If you provide some characters that are saying that UTF-8 error (not necessarily any that are in your password), I'll be able to debug it." Carson McManus's.

Characters from the password: space and Russian alphabet lowercase.

**Comment by Infantile-bastard** [comment]
"This is a bug in steamguard-cli. Please file an issue on github. If you provide some characters that are saying that UTF-8 error (not necessarily any that are in your password), I'll be able to debug it." Carson McManus's

- Characters from the password: space and Russian alphabet lowercase.

**Comment by Infantile-bastard** [comment]
Both options

**Comment by Infantile-bastard** [comment]
In my password: English and Russian alphabet characters and **there is a space.**

When I enter only the English alphabet, it gives a logical error 
ERROR Incorrect password for *********

But if I write any character of the Russian alphabet:
ERROR prompting for passkey
Caused by:
    stream did not contain valid UTF-8

Is it possible to add reading of Russian characters?

**Comment by dyc3** [comment]
That's the thing, it works fine for me.

I think the default windows terminal might not properly support unicode. Try using the newer Windows Terminal instead: https://aka.ms/terminal

**Comment by Infantile-bastard** [comment]
I tried it from a new terminal.

![image](https://github.com/user-attachments/assets/e6172036-660e-4ea7-9033-32b666467eb5)

Maybe I'm doing something wrong?

**Comment by dyc3** [comment]
Try passing in your password as a CLI argument.

```
steamguard --username foo --password bar confirm
```

**Comment by Infantile-bastard** [comment]
The red bracket is the password. there is a space between the English and Russian characters.

I'm entering the correct username.

![image](https://github.com/user-attachments/assets/93ac46ef-0d63-461b-b31d-47ee4e97656f)

**Comment by dyc3** [comment]
put it in quotes: `--password "whole password"`

**Comment by Infantile-bastard** [comment]
![image](https://github.com/user-attachments/assets/9b13b870-8f8f-47e4-b092-9b0057e08d67)


.
.

Everything worked with the other account. But there are no Russian characters in the password.

![image](https://github.com/user-attachments/assets/22cd28a5-e0c0-4388-b40f-debd6f3e012f)

**Comment by Infantile-bastard** [comment]
As I set 65001, the error is removed, but the password is still considered incorrect. Apparently, you will have to untie the SDA and get two weeks of ban...

![image](https://github.com/user-attachments/assets/93fc2084-f2b2-41cf-871c-72aee36dea4e)

**Comment by dyc3** [comment]
Yeah sorry, I have no idea what's going on with this one. Most of the stuff I'm seeing indicates that it could have something to do with region/locale settings in windows, so you could try setting your region to the US to see if that works. Otherwise, I got nothing.
