### ISSUE TITLE
I am not receiving an SMS to a Russian phone number.

### ISSUE THREAD

**Issue by Infantile-bastard** [dyc3/steamguard-cli#420]
### Version

steamguard-cli 0.14.2

### What happened?

Hi, it's me again, I had to delete the SDA completely, I'm trying to register a new account, but I'm not getting an SMS to a Russian phone number. I've already tried it twice.

![image](https://github.com/user-attachments/assets/132798f5-7b23-4373-97b8-f867403c96b9)

**Comment by dyc3** [comment]
Last time I checked, you don't need to have a phone number on the account to set up 2fa. You can try removing the phone number and then setting it up.

**Comment by Infantile-bastard** [comment]
Should I delete it from the steam? I have an error again already inside it. Because they just don't send SMS to the phone number

**Comment by dyc3** [comment]
Yeah, you can try removing the phone number from the account.

> I have an error again already inside it. 

What do you mean by this?

**Comment by Infantile-bastard** [comment]
This has been happening for the second day, there are just no messages coming.

![image](https://github.com/user-attachments/assets/916e01f5-057e-4b6f-96f2-5744d9eaf636)

**Comment by dyc3** [comment]
I can't fix valve not sending you SMS. That is on Valve's side.
