### ISSUE TITLE
Autoconfirm every x seconds

### ISSUE THREAD

**Issue by 16546489** [dyc3/steamguard-cli#426]
### Description

Will you add an option where we can set a time interval where confirmations will be accepted for that selected account? So we could set for 20 seconds and every 20 seconds the program would accept the confirmations that came in it would be helpful for listing up stuff on the market in bulk for example.

**Comment by dyc3** [comment]
No. You can easily do this already by scripting with bash or powershell.

linux/mac:
```
while true; do steamguard trade --accept-all; sleep 30; done
```

windows powershell:
```powershell
while ($true) { steamguard trade --accept-all; Start-Sleep -Seconds 30 }
```

**Comment by 16546489** [comment]
Thanks a lot!
