### ISSUE TITLE
Failed to migrate manifest Linux Mint

### ISSUE THREAD

**Issue by johnnafter** [dyc3/steamguard-cli#427]
### Version

steamguard-cli 0.14.2

### What happened?

Issue with decryption(?) Previously using steamguard desktop authenticator, moved to Linux Mint. Tried to import maFiles. (I've used steamguard-cli on Windows before moving to Linux, and it worked without any problems. So I think it's only specific to Linux)

### Steps To Reproduce

OS: Linux Mint 22 x86_64
Shell: bash 5.2.21

### Relevant log output

```Shell
john@Mint:~$ steamguard -m "/home/john/.config/steamguard-cli/maFiles" -v debug
DEBUG Args { global: GlobalArgs { username: None, password: None, all: false, mafiles_path: Some("/home/john/.config/steamguard-cli/maFiles"), passkey: None, verbosity: Debug, no_update_check: false, http_proxy: None, proxy_credentials: None, danger_accept_invalid_certs: false }, sub: None, code: CodeCommand { offline: false } }
INFO reading manifest from /home/john/.config/steamguard-cli/maFiles
DEBUG loading manifest: "/home/john/.config/steamguard-cli/maFiles/manifest.json"
INFO Migrating manifest
DEBUG deserializing manifest: version None


ERROR Failed to migrate manifest: An unexpected error occurred during manifest migration: Failed to load some accounts: [DecryptionFailed(Unknown(Unpad Error)), DecryptionFailed(Unknown(Unpad Error))]

Caused by:
Failed to load some accounts: [DecryptionFailed(Unknown(Unpad Error)), DecryptionFailed(Unknown(Unpad Error))]

DEBUG Checking for updates to dyc3/steamguard-cli v0.14.2
DEBUG No update available
```

**Comment by dyc3** [comment]
The decryption should work the same on windows and linux. Do the exact same set of maFiles work on windows with this version of steamguard-cli?

**Comment by johnnafter** [comment]
Yes, it works on windows. I've triple-checked to ensure it's the correct password. I've also tried to use this program on another window's machine again just for good measure, and it worked fine.
