### ISSUE TITLE
How to use winauth's backup file on steamguard-cli

### ISSUE THREAD

**Issue by salahmak** [dyc3/steamguard-cli#45]
Hello, before switching to linux I had winauth, and i've exported the recovery file from there (not encrypted), it has output like this:
`optauth:<some long string for the steam guard info>`

So now, on linux, I can't use winauth, so i had to use steamguard-cli, but i have no idea how to use the old winauth export file in this tool, i've tried putting it on the ~/maFiles folder, but still didn't work. Would be so happy if there is a way to transfer steam auth from winauth to steamguard without going through the process of recovering my steam account, bcs i can't even access it at this point.
Thanks

**Comment by dyc3** [comment]
steamguard-cli uses the same file format as https://github.com/Jessecar96/SteamDesktopAuthenticator. It can't import winauth exports at this time. I've never used winauth before, but it is open source: https://github.com/winauth/winauth. You could see how it stores that stuff here maybe: https://github.com/winauth/winauth/blob/master/WinAuth/AddSteamAuthenticator.cs

**Comment by salahmak** [comment]
> steamguard-cli uses the same file format as https://github.com/Jessecar96/SteamDesktopAuthenticator. It can't import winauth exports at this time. I've never used winauth before, but it is open source: https://github.com/winauth/winauth. You could see how it stores that stuff here maybe: https://github.com/winauth/winauth/blob/master/WinAuth/AddSteamAuthenticator.cs

Well, I have solved it, the steamguard-cli's maFile has a json object with those required keys, so I opened my winauth backup file and got those variables from it and it, and wrote them in the maFile's json object, and it worked. Thanks for replying
