### ISSUE TITLE
error: No accounts read. On arch linux

### ISSUE THREAD

**Issue by JapaneseText** [dyc3/steamguard-cli#46]
This error showed up after a previous error about not being able to get access to somewhere, so i ran `build/steamguard` using sudo, and this error appears even if I run it normally.
```
0024:err:module:open_builtin_file failed to load .so lib "/usr/lib32/wine/l3codeca.acm.so"
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00c8:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0B9FE338, 0BF03080, 0B9FE33C, 0B9FE330
00c8:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0B9FE338, 0BF03080, 0B9FE33C, 0B9FE330
error: No accounts read.
```

**Comment by dyc3** [comment]
The default location it looks for the manifest is `~/maFiles`.

**Comment by chdktomar** [comment]
I am also having the same error on MAC. Getting `$error: No accounts read.` after `mono build/steamguard`

**Comment by dyc3** [comment]
Where is your maFiles folder?

**Comment by chdktomar** [comment]
At home directory, with only one file in it named menifest.json.

**Comment by dyc3** [comment]
Ah, well that's the problem. If you've added any accounts, it should contain `manifest.json` and at least one file ending in `.maFile`.

**Comment by chdktomar** [comment]
How can I add any account with configuring stream-cli?? Please help.

**Comment by dyc3** [comment]
If you have the .maFile, you can manually add it to the manifest.json in the `entries` array by adding an object like this:

```json
{"encryption_iv":null,"encryption_salt":null,"filename":"FILENAME.maFile","steamid":56529601058667346}
```

**Comment by JapaneseText** [comment]
I see, I'll mark this issue as closed for now
