### ISSUE TITLE
/etc/bash_completion.d may not exist on macos

### ISSUE THREAD

**Issue by michaelshumshum** [dyc3/steamguard-cli#47]
hey there sir.
this is a great project you got going.
anyway, I'm tryna get this to work on mac and need some help after the building it. 

running `mono build/steamguard` gives me `error: No accounts read.`

running the one after that is has the same outcome.

running `make -f makefile.macos install` gives me error 
`cp: /etc/bash_completion.d/steamguard: No such file or directory
make: *** [install] Error 1`

in the installation section, i don't even know what to do. i don't think I'm supposed to do the debian package part and the `sudo make install` gives me the same error as before.

I'm not that experienced with this kinda stuff so any help would be appreciated.

**Comment by dyc3** [comment]
I don't exactly have a mac to test with, and I'm not super familiar with the platform. The documentation and makefile was provided by @spkane. 

That being said, `mono build/steamguard` should give `error: No accounts read` if you haven't set up any accounts yet. By default, it looks for a manifest file with all the accounts at the path `~/maFiles/manifest.json`. If you've used SDA, you should just be able to use the same `maFiles` from that. If not, you can set up a new account with `mono bin/steamguard setup`.

Does `/etc/bash_completion.d` exist on mac?

**Comment by michaelshumshum** [comment]
`/etc/bash_completion.d` doesn't exist at all. there is a file named `bash_completion`.

**Comment by dyc3** [comment]
As a workaround, you could create it. I don't know if that will actually make the bash completion work, but it's not required for the actual program to work.

**Comment by michaelshumshum** [comment]
ok thanks for the help.
though, one thing I'm encountering while doing the steamguard setup is adding the phone number returns `GeneralFailure`. i get an email to confirm adding this phone number. should i just added my phone number to the account manually then?

**Comment by dyc3** [comment]
That's probably #41

**Comment by michaelshumshum** [comment]
the `bash_completion.d` has been pushed and it seems to work fine on my side.

**Comment by melvyn2** [comment]
HI, 
Generally, software built locally should be installed to the `/usr/local` prefix (on all unix systems). Therefore, bash completion scripts should be installed to `/usr/local/etc/bash_completion.d`. This path exists on my system, but do note that I had installed it with homebrew.

**Comment by dyc3** [comment]
Closing because it's no longer relevant.
