### ISSUE TITLE
Parsing arguments [suggestion]

### ISSUE THREAD

**Issue by mtheos** [dyc3/steamguard-cli#51]
Have you considered Mono.Options for parsing CLI args in C#?

It's been a while since I've done something like this, and I don't know what competitors are around, but it was easy and intuitive to use when I needed it.

Here is an STO [link](https://stackoverflow.com/a/2067916/5699459) showing an example usage of Mono.Options

**Comment by dyc3** [comment]
If I were building this now, that would probably be something I'd use. But it's not something I want to switch to now, considering what I've already written works, and adding another dependency sounds painful with how my builds are set up.

**Comment by mtheos** [comment]
Understandable, I just mentioned it because the project looks active and you have a TODO comment regarding args.
