### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by rinates** [dyc3/steamguard-cli#52]
I'm using Ubuntu 20.04. When I try to make this one, I have it:
How to fix? 
```
mkdir -p build/
nuget restore SteamAuth/SteamAuth/SteamAuth.sln
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
All packages listed in packages.config are already installed.
echo "NEWTONSOFT_JSON_PATH=./SteamAuth/SteamAuth/packages/Newtonsoft.Json.12.0.3/lib/net45/Newtonsoft.Json.dll"
NEWTONSOFT_JSON_PATH=./SteamAuth/SteamAuth/packages/Newtonsoft.Json.12.0.3/lib/net45/Newtonsoft.Json.dll
mcs -target:library -out:build/SteamAuth.dll -r:./SteamAuth/SteamAuth/packages/Newtonsoft.Json.12.0.3/lib/net45/Newtonsoft.Json.dll SteamAuth/SteamAuth/APIEndpoints.cs SteamAuth/SteamAuth/AuthenticatorLinker.cs SteamAuth/SteamAuth/Confirmation.cs SteamAuth/SteamAuth/SessionData.cs SteamAuth/SteamAuth/SteamGuardAccount.cs SteamAuth/SteamAuth/SteamWeb.cs SteamAuth/SteamAuth/TimeAligner.cs SteamAuth/SteamAuth/UserLogin.cs SteamAuth/SteamAuth/Util.cs SteamAuth/SteamAuth/Properties/AssemblyInfo.cs
SteamAuth/SteamAuth/SteamGuardAccount.cs(330,20): warning CS0219: The variable `referer' is assigned but its value is never used
SteamAuth/SteamAuth/SteamGuardAccount.cs(350,20): warning CS0219: The variable `referer' is assigned but its value is never used
SteamAuth/SteamAuth/SteamGuardAccount.cs(371,20): warning CS0219: The variable `referer' is assigned but its value is never used
SteamAuth/SteamAuth/UserLogin.cs(75,38): warning CS0219: The variable `secureRandom' is assigned but its value is never used
Compilation succeeded - 4 warning(s)
cp ./SteamAuth/SteamAuth/packages/Newtonsoft.Json.12.0.3/lib/net45/Newtonsoft.Json.dll build/
mcs -out:build/steamguard -r:build/SteamAuth.dll -r:build/Newtonsoft.Json.dll -r:/usr/lib/mono/4.5/System.Security.dll Program.cs Manifest.cs AssemblyInfo.cs Utils.cs

```

**Comment by Pingger** [comment]
This actually looks like it compile successfully.
There is nothing to fix!

**Comment by rinates** [comment]
> This actually looks like it compiled successfully.
> There is nothing to fix!
> 
> Maybe take a look at this again? (aka the Readme!)
> https://github.com/dyc3/steamguard-cli#linux

Ye, I see. I thought It could be some errors. So, is it normal like this? 

Username: awidjiauwjd222
Password: Password: 

I don't see my password.

**Comment by Pingger** [comment]
it is intended to hide the password! As with every other properly developed software

**Comment by rinates** [comment]
> it is intended to hide the password! As with every other properly developed software

I see, but it looks weird. I mean ":" after password. I think, will be better if user has a choose to hide or not the password.

**Comment by Pingger** [comment]
Why go against all established standards?!
Linux login does same exact thing. Additionally these also do the same:
sudo
steamcmd
chpasswd
runas
...

**Comment by rinates** [comment]
> Why go against all established standards?!
> Linux login does same exact thing. Additionally these also do the same:
> sudo
> steamcmd
> chpasswd
> runas
> ...

Username: awidjiauwjd222
Password: Password:

I mean, that the string of password is duplicated.

**Comment by dyc3** [comment]
Did you run `sudo make install` yet?

**Comment by rinates** [comment]
> Did you run `sudo make install` yet?

Ye, it already woks good. I've tied several accounts. But I cannot find out why "Password:" is duplicated.

**Comment by rinates** [comment]
That's it. I fixed in Utils.

**Comment by dyc3** [comment]
Then I'll close the issue.
