### ISSUE TITLE
zsh: Ошибка формата выполняемого файла: build/steamguard

### ISSUE THREAD

**Issue by crsov** [dyc3/steamguard-cli#53]
zsh: Ошибка формата выполняемого файла: build/steamguard

**Comment by dyc3** [comment]
Can you please use english? And could you elaborate a bit more about what your environment is like, and the steps you took?

**Comment by crsov** [comment]
First i installed depends
second i ran this
git clone --recursive https://github.com/dyc3/steamguard-cli.git
cd steamguard-cli
make
chmod +x build/steamguard
 Now tried to start by build/steamguard, but had  zsh: Ошибка формата выполняемого файла: build/steamguard error
 I tried to re-chmod in build dir:
cd build
chmod +x steamguard (also ./steamguard)
./steamguard
Same error: zsh: Ошибка формата выполняемого файла: build/steamguard in english zsh: Executable file format error: Build/Steamguard
nuget/mono/mono-msbuild installed

**Comment by dyc3** [comment]
For reference: the russian error message google translates to `Executable file format error`.

What OS and version are you using? What hardware are you using (CPU in particular)?

**Comment by crsov** [comment]
......                crsov@crsohost
         .'Dlddddddddddd'.           OS: Solus 4.1 fortitude
      .'dddXMxdddddddddddddd.        Kernel: x86_64 Linux 5.10.7-168.current
    .dddddxMMM0;dddddddddddddd.      Uptime: 5h 15m
   'dddddlMMMMMNcddddddddddddddd.    Packages: 1229
  ddddddcWMMMMMMWlddddddddddddddd.   Shell: zsh 5.8
 ddddddcWMMMMMMMMOddoddddddddddddd.  Resolution: 1920x1080
.ddddd:NMMMMMMMMMKddNXod;clxldddddd  DE: GNOME 3.38.3
dddddcWMMMMMMMMMMNNddMMXl;d00xl;ddd. WM: BudgieWM
ddddlWMMMMMMMMMMMMMd;MMMM0:dlXMMXk:' WM Theme: Plata-Noir
dddoWMMMMMMMMMMMMMMddMMMMMWod;XMMMOd GTK Theme: Vimix-light-doder [GTK2/3]
.ddMMMMMMMMMMMMMMMMd:MMMMMMMkdlMKll  Icon Theme: Sardi-Arc
.;dk0KXNWWMMMMMMMMMdxMMMMMMMXl;lxK;  Font: Noto Sans 9
  'dddddddd;:cclodcddxddolloxO0Od'   Disk: 33G / 419G (9%)
   ckkxxxddddddddxxkOOO000Okdool.    CPU: Intel Core i5-1035G1 @ 8x 3.6GHz [73.0°C]
    .lddddxxxxxxddddooooooooood      GPU: Mesa Intel(R) UHD Graphics (ICL GT1)
      .:oooooooooooooooooooc'        RAM: 2236MiB / 7727MiB
         .,:looooooooooc;.

**Comment by dyc3** [comment]
does `mono build/steamguard` produce the same error?

**Comment by crsov** [comment]
It gives error: No accounts read error

**Comment by dyc3** [comment]
Ok, then it's running as intended when you run it with `mono`. Use that as a work around, I'm not entirely sure why its not working without mono for you. I don't have a Solus install immediately ready so I can't do much to troubleshoot more right now.

Run `mono build/steamguard setup` to set up the authenticator if you haven't already.

**Comment by crsov** [comment]
Thx
