### ISSUE TITLE
Missing file problem

### ISSUE THREAD

**Issue by MissXecutioner** [dyc3/steamguard-cli#64]
error CS0009: Metadata file `/root/steamguard-cli/./SteamAuth/SteamAuth/packages                                                                                                                                                             /Newtonsoft.Json.12.0.3/lib/net45/Newtonsoft.Json.dll' does not contain valid me                                                                                                                                                             tadata
Compilation failed: 1 error(s), 0 warnings
error CS0006: Metadata file `build/SteamAuth.dll' could not be found
error CS0009: Metadata file `/root/steamguard-cli/build/Newtonsoft.Json.dll' doe                                                                                                                                                             s not contain valid metadata
Compilation failed: 2 error(s), 0 warnings

**Comment by Pingger** [comment]
Just in case someone else stumbles upon this issue, maybe you can provide your solution?
